import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox','--allow-file-access-from-files'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs = [];
p.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto('file:///home/user/teste/wobble-rush/wobble-rush.html', { waitUntil: 'load' });
await p.waitForTimeout(3000);
await p.screenshot({ path: '/tmp/claude-0/single-menu.png' });
const hasPlay = await p.$('#play');
await p.click('#play').catch(() => {});
await p.waitForTimeout(9000);
await p.keyboard.down('KeyW');
await p.waitForTimeout(3000);
await p.screenshot({ path: '/tmp/claude-0/single-match.png' });
console.log('menu loaded:', hasPlay ? 'OK' : 'FAIL', '| errors:', errs.length ? errs.slice(0,5).join(' | ') : 'none');
await b.close();
