import { chromium } from 'playwright-core';
const url = process.argv[2] || 'http://localhost:4173/?debug=1&quality=high';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto(url);
await p.waitForFunction(() => window.__ready === true, null, { timeout: 240000 });
const ev = (f, a) => p.evaluate(f, a);
const shot = async (n) => { await ev(() => __debug.renderOnce(0)); await p.screenshot({ path: `test-output/rv_${n}.png`, timeout: 240000 }); };
const check = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) process.exitCode = 1; };
await ev(() => { __debug.freeze(true); __debug.newGame('normal'); __debug.setTime(8.4); });
await ev(() => { const r = __game.rover; __debug.teleport(r.pos.x + 5.5, r.pos.z + 4); __game.player.yaw = Math.atan2(-(r.pos.x - __game.player.pos.x), -(r.pos.z - __game.player.pos.z)) + 0.35; __debug.camDist(5); __game.player.pitch = -0.12; });
await ev(() => __debug.renderOnce(2));
const r0 = await ev(() => ({ pos: __game.rover.pos.toArray(), up: !__game.rover.isFlipped() }));
check(r0.up, `rover estável parado (y=${r0.pos[1].toFixed(2)})`);
await shot('01_rover_parado');
await ev(() => { const r = __game.rover; __debug.teleport(r.pos.x + 2.5, r.pos.z); });
await ev(() => __debug.renderOnce(0.2));
await ev(() => __game.input.fire('vehicle'));
await ev(() => __debug.renderOnce(0.2));
check(await ev(() => __game.driving), 'entrou no rover (F)');
await ev(() => { __game.input.move.y = 1; });
await ev(() => __debug.renderOnce(6));
const r1 = await ev(() => ({ pos: __game.rover.pos.toArray(), speed: __game.rover.speed, up: !__game.rover.isFlipped(), batt: __game.rover.battery }));
const d = Math.hypot(r1.pos[0] - r0.pos[0], r1.pos[2] - r0.pos[2]);
check(d > 10 && r1.up, `andou ${d.toFixed(1)} m em 6 s, ${(r1.speed * 3.6).toFixed(1)} km/h, de pé=${r1.up}, bateria ${r1.batt.toFixed(2)}`);
await ev(() => { __game.input.move.x = 0.7; });
await ev(() => __debug.renderOnce(2));
await shot('02_dirigindo');
await ev(() => { __game.input.move.x = 0; __game.input.move.y = 0; __game.input.setHeld('jump', true); });
await ev(() => __debug.renderOnce(4));
await ev(() => __game.input.setHeld('jump', false));
const sp = await ev(() => __game.rover.speed);
check(Math.abs(sp) < 0.6, `freou (${sp.toFixed(2)} m/s)`);
await ev(() => { __debug.setTime(21); __game.rover.setLights(true); });
await ev(() => __debug.renderOnce(0.5));
await shot('03_farois_noite');
await ev(() => __game.input.fire('vehicle'));
await ev(() => __debug.renderOnce(0.3));
const ex = await ev(() => ({ driving: __game.driving, g: __game.player.grounded, y: __game.player.pos.y, h: __game.terrain.heightAt(__game.player.pos.x, __game.player.pos.z) }));
check(!ex.driving && ex.y > ex.h - 0.2, `saiu do rover, no chão (y ${ex.y.toFixed(2)} / solo ${ex.h.toFixed(2)})`);
console.log('erros:', errs.join('\n') || 'nenhum');
await b.close();
