/**
 * Todos os textos de interface em pt-BR — CLAUDE.md §4.
 * Nada de string solta em JSX. Voz: direta, informativa, sem infantilizar (docs/03 §6).
 */
export const copy = {
  marca: {
    nome: "BeautyNow",
    slogan: "Cosméticos profissionais, curadoria de verdade.",
  },
  header: {
    busca: "Buscar produto, marca ou necessidade",
    minhaConta: "Minha conta",
    sacola: "Sacola",
    menu: "Menu",
    fecharMenu: "Fechar menu",
    anuncio: "Frete grátis a partir de R$ 199 · Pix com 5% de desconto · Envio em até 24h",
  },
  nav: {
    categorias: "Categorias",
    marcas: "Marcas",
    necessidades: "Por necessidade",
    todasMarcas: "Ver todas as marcas",
  },
  home: {
    heroTitulo: "Seu cabelo, tratado como em salão.",
    heroTexto:
      "Selecionamos o melhor do haircare e do skincare profissional para você usar em casa, com orientação de quem distribui essas marcas há 15 anos.",
    heroCta: "Ver mais vendidos",
    heroCtaSecundario: "Montar minha rotina",
    maisVendidos: "Mais vendidos",
    lancamentos: "Lançamentos",
    porCategoria: "Compre por categoria",
    porNecessidade: "O que seu cabelo precisa hoje?",
    marcasDestaque: "Marcas que a gente confia",
    verTudo: "Ver tudo",
    seloOriginal: "Distribuidor autorizado",
    seloOriginalTexto: "Produto 100% original, direto do fabricante.",
    seloEnvio: "Envio em até 24h",
    seloEnvioTexto: "Pedidos aprovados até 15h saem no mesmo dia.",
    seloTroca: "Troca fácil em 7 dias",
    seloTrocaTexto: "Sem burocracia, conforme o CDC.",
    seloPix: "5% off no Pix",
    seloPixTexto: "Desconto aplicado no total do pedido.",
    newsletterTitulo: "Receba ofertas e rotinas por e-mail",
    newsletterTexto: "Sem spam. Só lançamento, reposição e conteúdo que ajuda.",
    newsletterPlaceholder: "seu@email.com",
    newsletterCta: "Quero receber",
    newsletterOk: "Pronto! Confira seu e-mail para confirmar a inscrição.",
  },
  card: {
    adicionar: "Adicionar",
    esgotado: "Esgotado",
    noPix: "no Pix",
    ate: "até",
    semJuros: "sem juros",
    tamanhos: "tamanhos",
    lancamento: "Lançamento",
  },
  plp: {
    filtros: "Filtros",
    limparFiltros: "Limpar filtros",
    ordenar: "Ordenar por",
    produtos: "produtos",
    produto: "produto",
    nenhumResultado: "Nenhum produto com esses filtros. Remova algum filtro para ampliar a busca.",
    filtroMarca: "Marca",
    filtroPreco: "Preço",
    filtroTipoCabelo: "Tipo de cabelo",
    filtroNecessidade: "Necessidade",
    filtroTipoPele: "Tipo de pele",
    filtroBeneficios: "Características",
    disponiveis: "Somente disponíveis",
    ordenacao: {
      relevancia: "Relevância",
      maisVendidos: "Mais vendidos",
      menorPreco: "Menor preço",
      maiorPreco: "Maior preço",
      lancamentos: "Lançamentos",
      melhorAvaliados: "Melhor avaliados",
    },
  },
  pdp: {
    adicionarSacola: "Adicionar à sacola",
    adicionado: "Adicionado à sacola",
    esgotado: "Produto esgotado",
    aviseMe: "Avise-me quando chegar",
    aviseMeOk: "Pronto! Você será avisada assim que o produto voltar.",
    quantidade: "Quantidade",
    calcularFrete: "Calcular frete e prazo",
    cepPlaceholder: "00000-000",
    cepErro: "CEP não encontrado. Confira os 8 dígitos.",
    calcular: "OK",
    avaliacoes: "avaliações",
    avaliacao: "avaliação",
    sobre: "Sobre o produto",
    comoUsar: "Como usar",
    composicao: "Composição",
    especificacoes: "Especificações",
    compreJunto: "Compre junto",
    compreJuntoDesconto: "Leve o combo com 10% de desconto",
    adicionarCombo: "Adicionar combo à sacola",
    mesmaLinha: "Da mesma linha",
    quemViuTambemViu: "Quem viu também viu",
    ultimasUnidades: (n: number) => `Últimas ${n} unidades`,
    emEstoque: "Em estoque",
    distribuidorAutorizado: "Distribuidor autorizado",
    trocaFacil: "Troca em 7 dias",
    envio24h: "Envio em 24h",
    compraVerificada: "Compra verificada",
    de: "de",
    noPix: "no Pix",
    off: "off",
    emAte: "em até",
    semJuros: "sem juros",
  },
  carrinho: {
    titulo: "Sua sacola",
    vazio: "Sua sacola está vazia. Comece pelos mais vendidos.",
    verMaisVendidos: "Ver mais vendidos",
    subtotal: "Subtotal",
    descontoPix: "Desconto Pix (5%)",
    totalNoPix: "Total no Pix",
    finalizarCompra: "Finalizar compra",
    continuarComprando: "Continuar comprando",
    remover: "Remover",
    freteGratisAtingido: "Você ganhou frete grátis!",
    freteGratisFaltam: (valor: string) => `Faltam ${valor} para frete grátis`,
    brindeAtingido: "Brinde garantido: Nécessaire BeautyNow",
    brindeFaltam: (valor: string) => `Faltam ${valor} para ganhar um brinde`,
    pedidoMinimo: (valor: string) => `Pedido mínimo de ${valor} para finalizar a compra`,
    fechar: "Fechar sacola",
  },
  checkout: {
    titulo: "Finalizar compra",
    identificacao: "Identificação",
    entrega: "Entrega",
    pagamento: "Pagamento",
    email: "E-mail",
    nome: "Nome completo",
    cpf: "CPF",
    telefone: "Celular (WhatsApp)",
    cep: "CEP",
    logradouro: "Endereço",
    numero: "Número",
    complemento: "Complemento (opcional)",
    bairro: "Bairro",
    cidade: "Cidade",
    uf: "UF",
    referencia: "Ponto de referência (opcional)",
    pix: "Pix",
    pixDetalhe: "Aprovação na hora · 5% de desconto",
    cartao: "Cartão de crédito",
    cartaoDetalhe: "Em até 6x sem juros",
    boleto: "Boleto à vista",
    boletoDetalhe: "Compensação em até 2 dias úteis",
    resumo: "Resumo do pedido",
    frete: "Frete",
    total: "Total",
    concluir: "Concluir pedido",
    seguro: "Ambiente seguro",
    atendimento: "Atendimento: (21) 99999-0000",
    continuar: "Continuar",
    voltarLoja: "Voltar para a loja",
    camposObrigatorios: "Preencha os campos destacados para continuar.",
  },
  confirmacao: {
    titulo: "Pedido recebido!",
    subtitulo: (numero: string) =>
      `Seu pedido ${numero} foi registrado. Enviamos a confirmação para o seu e-mail.`,
    pixTitulo: "Pague com Pix para aprovar na hora",
    pixCopiar: "Copiar código Pix",
    pixCopiado: "Código copiado!",
    prazo: "Prazo estimado de entrega",
    acompanhar: "Acompanhar pedido",
  },
  rodape: {
    institucional: "Institucional",
    ajuda: "Ajuda",
    pagamento: "Pagamento",
    seguranca: "Segurança",
    quemSomos: "Quem somos",
    trocasDevolucoes: "Trocas e devoluções",
    politicaPrivacidade: "Política de privacidade",
    termosUso: "Termos de uso",
    politicaEntrega: "Política de entrega",
    faq: "Perguntas frequentes",
    contato: "Fale com a gente",
    rastrearPedido: "Rastrear pedido",
    cnpj: "BeautyNow Cosméticos LTDA · CNPJ 00.000.000/0001-00",
    endereco: "Rio de Janeiro, RJ",
    direitos: `© ${new Date().getFullYear()} BeautyNow. Todos os direitos reservados.`,
  },
  busca: {
    titulo: "Resultados para",
    placeholder: "Buscar produto, marca ou necessidade",
    nenhum: (termo: string) =>
      `Nenhum resultado para "${termo}". Confira a digitação ou navegue pelas categorias.`,
    sugestoes: "Sugestões",
    verTodos: "Ver todos os resultados",
  },
  conta: {
    titulo: "Minha conta",
    texto:
      "A área do cliente (pedidos, rastreio, endereços e favoritos) chega com a integração do backend — Sprint 5 do roadmap.",
  },
} as const;
