import { LOJA } from "@/lib/loja";

/**
 * Todos os textos de interface em pt-BR — CLAUDE.md §4.
 * Nada de string solta em JSX. Voz: direta, informativa, sem infantilizar (docs/03 §6).
 * Textos que mudam entre BeautyNow e Be2Beauty usam LOJA.b2b.
 */
export const copy = {
  marca: {
    nome: LOJA.nome,
    slogan: LOJA.b2b
      ? "O e-commerce do cabeleireiro."
      : "Cosméticos profissionais, curadoria de verdade.",
  },
  header: {
    busca: "Buscar produto, marca ou necessidade",
    minhaConta: "Minha conta",
    sacola: "Sacola",
    menu: "Menu",
    fecharMenu: "Fechar menu",
    anuncio: LOJA.b2b
      ? "Site exclusivo para profissionais da beleza com CNPJ/MEI · Cadastre-se e libere os preços"
      : "Pix com 5% de desconto · Produtos 100% originais",
  },
  nav: {
    inicio: "Início",
    categorias: "Categorias",
    marcas: "Marcas",
    necessidades: "Por necessidade",
    todasMarcas: "Ver todas as marcas",
  },
  home: {
    heroTitulo: "Seu cabelo, tratado como em salão.",
    heroTexto:
      "Selecionamos o melhor do haircare profissional, da perfumaria e do cuidado pessoal para você usar em casa, com orientação de quem distribui essas marcas há 15 anos.",
    heroCta: "Ver mais vendidos",
    maisVendidos: "Mais vendidos",
    lancamentos: "Lançamentos",
    porCategoria: "Compre por categoria",
    porNecessidade: "O que seu cabelo precisa hoje?",
    marcasDestaque: "Marcas que a gente confia",
    verTudo: "Ver tudo",
    seloOriginal: "Distribuidor autorizado",
    seloOriginalTexto: "Produto 100% original, direto do fabricante.",
    seloEnvio: "Envio rápido",
    seloEnvioTexto: "Despachamos para todo o Brasil com rastreio ponta a ponta.",
    seloTroca: "Troca fácil em 7 dias",
    seloTrocaTexto: "Sem burocracia, conforme o CDC.",
    seloPix: "5% off no Pix",
    seloPixTexto: "Desconto aplicado no total do pedido.",
    newsletterTitulo: "Receba ofertas e novidades por e-mail",
    newsletterTexto: "Sem spam. Só lançamento, reposição e conteúdo que ajuda.",
    newsletterPlaceholder: "seu@email.com",
    newsletterCta: "Quero receber",
    newsletterOk: "Pronto! Confira seu e-mail para confirmar a inscrição.",
  },
  card: {
    adicionar: "Adicionar",
    esgotado: "Esgotado",
    noPix: "no Pix",
    ate: "até",
    semJuros: "sem juros",
    tamanhos: "tamanhos",
    lancamento: "Lançamento",
  },
  plp: {
    filtros: "Filtros",
    limparFiltros: "Limpar filtros",
    ordenar: "Ordenar por",
    produtos: "produtos",
    produto: "produto",
    nenhumResultado: "Nenhum produto com esses filtros. Remova algum filtro para ampliar a busca.",
    filtroMarca: "Marca",
    filtroPreco: "Preço",
    filtroTipoCabelo: "Tipo de cabelo",
    filtroNecessidade: "Necessidade",
    filtroTipoPele: "Tipo de pele",
    filtroBeneficios: "Características",
    disponiveis: "Somente disponíveis",
    ordenacao: {
      relevancia: "Relevância",
      maisVendidos: "Mais vendidos",
      menorPreco: "Menor preço",
      maiorPreco: "Maior preço",
      lancamentos: "Lançamentos",
      melhorAvaliados: "Melhor avaliados",
    },
  },
  pdp: {
    adicionarSacola: "Adicionar à sacola",
    adicionado: "Adicionado à sacola",
    esgotado: "Produto esgotado",
    aviseMe: "Avise-me quando chegar",
    aviseMeOk: "Pronto! Você será avisada assim que o produto voltar.",
    quantidade: "Quantidade",
    calcularFrete: "Calcular frete e prazo",
    cepPlaceholder: "00000-000",
    cepErro: "CEP não encontrado. Confira os 8 dígitos.",
    calcular: "OK",
    avaliacoes: "avaliações",
    avaliacao: "avaliação",
    sobre: "Sobre o produto",
    comoUsar: "Como usar",
    composicao: "Composição",
    especificacoes: "Especificações",
    compreJunto: "Compre junto",
    compreJuntoDesconto: "Leve o combo com 10% de desconto",
    adicionarCombo: "Adicionar combo à sacola",
    mesmaLinha: "Da mesma linha",
    quemViuTambemViu: "Quem viu também viu",
    ultimasUnidades: (n: number) => `Últimas ${n} unidades`,
    emEstoque: "Em estoque",
    distribuidorAutorizado: "Distribuidor autorizado",
    trocaFacil: "Troca em 7 dias",
    envioRapido: "Envio rápido",
    compraVerificada: "Compra verificada",
    de: "de",
    noPix: "no Pix",
    off: "off",
    emAte: "em até",
    semJuros: "sem juros",
  },
  carrinho: {
    titulo: "Sua sacola",
    vazio: "Sua sacola está vazia. Comece pelos mais vendidos.",
    verMaisVendidos: "Ver mais vendidos",
    subtotal: "Subtotal",
    descontoPix: "Desconto Pix (5%)",
    totalNoPix: "Total no Pix",
    finalizarCompra: "Finalizar compra",
    continuarComprando: "Continuar comprando",
    remover: "Remover",
    brindeAtingido: "Brinde garantido: Nécessaire BeautyNow",
    brindeFaltam: (valor: string) => `Faltam ${valor} para ganhar um brinde`,
    pedidoMinimo: (valor: string) => `Pedido mínimo de ${valor} para finalizar a compra`,
    fechar: "Fechar sacola",
    cupomTitulo: "Tem cupom de desconto?",
    cupomPlaceholder: "Digite o código",
    cupomAplicar: "Aplicar",
    cupomAplicado: (codigo: string) => `Cupom ${codigo} aplicado`,
    cupomRemover: "Remover cupom",
    cupomDesconto: "Desconto do cupom",
  },
  checkout: {
    titulo: "Finalizar compra",
    identificacao: "Identificação",
    entrega: "Entrega",
    pagamento: "Pagamento",
    email: "E-mail",
    nome: "Nome completo",
    cpf: "CPF",
    telefone: "Celular (WhatsApp)",
    cep: "CEP",
    logradouro: "Endereço",
    numero: "Número",
    complemento: "Complemento (opcional)",
    bairro: "Bairro",
    cidade: "Cidade",
    uf: "UF",
    referencia: "Ponto de referência (opcional)",
    pix: "Pix",
    pixDetalhe: "Aprovação na hora · 5% de desconto",
    cartao: "Cartão de crédito ou débito",
    cartaoDetalhe: "Crédito em até 6x sem juros · débito à vista",
    boleto: "Boleto à vista",
    boletoDetalhe: "Compensação em até 2 dias úteis",
    resumo: "Resumo do pedido",
    frete: "Frete",
    desconto: "Desconto do cupom",
    total: "Total",
    concluir: "Concluir pedido",
    seguro: "Ambiente seguro",
    atendimento: "Atendimento: (21) 99732-2464",
    continuar: "Continuar",
    voltarLoja: "Voltar para a loja",
    camposObrigatorios: "Preencha os campos destacados para continuar.",
  },
  confirmacao: {
    titulo: "Pedido recebido!",
    tituloAguardando: "Esperando pagamento…",
    subtitulo: (numero: string) =>
      `Seu pedido ${numero} foi registrado. Enviamos a confirmação para o seu e-mail.`,
    subtituloAguardando: (numero: string) =>
      `Seu pedido ${numero} foi registrado e será confirmado assim que o pagamento cair.`,
    pixTitulo: "Pague com Pix para aprovar na hora",
    pixCopiar: "Copiar código Pix",
    pixCopiado: "Código copiado!",
    prazo: "Prazo estimado de entrega",
    acompanhar: "Acompanhar pedido",
  },
  avaliacoes: {
    titulo: "Avaliações da loja",
    subtitulo: "O que nossas clientes dizem sobre os produtos e a experiência de compra.",
    deixeAvaliacao: "Deixe sua avaliação",
    suaNota: "Sua nota",
    notaProduto: "Nota para o produto",
    notaExperiencia: "Nota para a experiência de compra",
    seuNome: "Seu nome",
    seuComentario: "Conte como foi (opcional)",
    enviar: "Enviar avaliação",
    enviando: "Enviando…",
    obrigado: "✅ Obrigado! Sua avaliação já está publicada.",
    falha: "Não foi possível enviar agora. Tente novamente.",
    escolhaEstrelas: "Escolha de 1 a 5 estrelas antes de enviar.",
    carregando: "Carregando avaliações…",
    sejaPrimeira: "Seja a primeira pessoa a avaliar a loja!",
    nenhumaAinda: "Nenhuma avaliação ainda — a sua pode ser a primeira.",
    avaliacao: "avaliação",
    avaliacoes: "avaliações",
    compraVerificada: "compra verificada",
    posCompraTitulo: "Como foi sua experiência?",
    posCompraTexto: "Avalie em segundos — isso ajuda outras clientes e a gente a melhorar.",
  },
  rodape: {
    institucional: "Institucional",
    ajuda: "Ajuda",
    pagamento: "Pagamento",
    seguranca: "Segurança",
    quemSomos: "Quem somos",
    trocasDevolucoes: "Trocas e devoluções",
    politicaPrivacidade: "Política de privacidade",
    termosUso: "Termos de uso",
    politicaEntrega: "Política de entrega",
    faq: "Perguntas frequentes",
    avaliacoes: "Avaliações da loja",
    contato: "Fale com a gente",
    rastrearPedido: "Rastrear pedido",
    cnpj: LOJA.b2b
      ? "Be2Beauty · O e-commerce do cabeleireiro · Exclusivo para CNPJ/MEI"
      : "BeautyNow Cosméticos · CNPJ 52.286.975/0001-21",
    endereco: "Rio de Janeiro, RJ · Atendimento: (21) 99732-2464",
    direitos: `© ${new Date().getFullYear()} ${LOJA.nome}. Todos os direitos reservados.`,
  },
  b2b: {
    precoFechado: "Preço para profissionais",
    liberarPrecos: "Cadastre seu CNPJ para ver os preços",
    aguardandoAprovacao: "Cadastro em análise — avisamos por e-mail quando for aprovado",
    recusado: "Cadastro não aprovado. Fale com a gente: (21) 99732-2464",
    paginaTitulo: "Cadastro profissional",
    paginaTexto:
      "A Be2Beauty vende exclusivamente para profissionais e lojistas. Cadastre o CNPJ do seu salão, clínica ou loja: após a aprovação, os preços e a compra ficam liberados neste navegador.",
    semCnpj: "Não tem CNPJ? Compre no varejo pela BeautyNow →",
    semCnpjUrl: "https://www.beautynowstore.com.br",
    cnpj: "CNPJ",
    razaoSocial: "Razão social",
    nomeResponsavel: "Nome do responsável",
    email: "E-mail",
    whatsapp: "WhatsApp",
    enviar: "Enviar cadastro",
    enviando: "Enviando…",
    enviadoOk: "✅ Cadastro recebido! Vamos analisar e avisar por e-mail.",
    cnpjInvalido: "CNPJ inválido — confira os 14 dígitos.",
    falha: "Não foi possível enviar agora. Tente novamente em instantes.",
    statusTitulo: "Situação do seu cadastro",
    statusPendente: "⏳ Em análise",
    statusAprovado: "✅ Aprovado — preços liberados!",
    statusRecusado: "❌ Não aprovado",
    verificarNovamente: "Verificar novamente",
    trocarCnpj: "Cadastrar outro CNPJ",
    admin: {
      titulo: "Profissionais (B2B)",
      texto: "Cadastros com CNPJ do site Be2Beauty. Aprovar libera os preços para o cliente.",
      vazio: "Nenhum cadastro ainda.",
      aprovar: "Aprovar",
      recusar: "Recusar",
      pendente: "Pendente",
      aprovado: "Aprovado",
      recusadoRotulo: "Recusado",
    },
    afiliado: {
      titulo: "Programa de afiliados",
      texto:
        "Divulgue a BeautyNow com o seu link. Cada compra feita por ele rende comissão para você — acompanhe tudo aqui.",
      gerarLink: "Gerar meu link de afiliado",
      gerando: "Gerando…",
      seuLink: "Seu link de afiliado",
      copiar: "Copiar link",
      copiado: "✅ Link copiado!",
      comoUsar:
        "Cole este link nos seus vídeos, bio e stories. Quem comprar por ele nos próximos 30 dias conta como venda sua.",
      suaComissao: (pct: number) => `Sua comissão: ${pct}% por venda paga`,
      cardVendas: "Vendas",
      cardVendido: "Total vendido",
      cardComissao: "Sua comissão",
      graficoTitulo: "Vendas por mês",
      vendasRecentes: "Vendas recentes",
      semVendas: "Nenhuma venda pelo seu link ainda. Compartilhe para começar!",
      atualizar: "Atualizar",
      falha: "Não foi possível carregar agora. Tente de novo em instantes.",
      saqueTitulo: "Resgatar comissão",
      saqueTexto:
        "O valor disponível é enviado por Pix para a chave que você informar. Depois de pedir, o pagamento é confirmado pela nossa equipe.",
      saqueDisponivel: "Disponível para saque",
      saqueAguardando: "Aguardando pagamento",
      saqueRecebido: "Já recebido",
      saqueChavePix: "Sua chave Pix",
      saqueValor: "Valor do saque (R$)",
      saquePedir: "Pedir saque",
      saquePedindo: "Enviando pedido…",
      saqueOk: "✅ Pedido de saque enviado! Você recebe um e-mail quando o Pix sair.",
      saqueSemSaldo: "Você ainda não tem saldo para sacar.",
      saqueHistorico: "Seus saques",
      saqueStatusPendente: "⏳ Aguardando",
      saqueStatusPago: "✅ Pago",
      saqueStatusRecusado: "❌ Recusado",
      admin: {
        titulo: "Afiliados",
        texto:
          "Profissionais aprovados que divulgam o BeautyNow. Defina a comissão (%) de cada um e acompanhe as vendas.",
        geralVendas: "Vendas por afiliados",
        geralVendido: "Total vendido",
        geralComissao: "Comissões a pagar",
        colComissao: "Comissão %",
        salvarPct: "Salvar",
        salvo: "✅",
        semCodigo: "ainda não gerou o link",
        vazio: "Nenhum afiliado ainda — aprove cadastros na aba Profissionais.",
        ultimasVendas: "Últimas vendas por link de afiliado",
        saquesTitulo: "Pedidos de saque",
        saquesTexto:
          "Faça o Pix para a chave informada e marque como pago. Recusar devolve o valor ao saldo do afiliado.",
        saquesPendentes: "Saques pendentes",
        aPagar: "A pagar agora",
        marcarPago: "Marcar como pago",
        recusarSaque: "Recusar",
        semSaques: "Nenhum pedido de saque.",
      },
    },
  },
  afiliado: {
    paginaTitulo: "Área do afiliado",
    paginaTexto:
      "Divulgue a BeautyNow com o seu link e ganhe comissão em cada venda. Entre com o e-mail cadastrado — o acesso funciona em qualquer aparelho, sem senha.",
    loginTitulo: "Entrar",
    loginTexto: "Digite o e-mail que você usou (ou vai usar) no cadastro de afiliado.",
    loginEmailRotulo: "E-mail",
    loginBotao: "Enviar código",
    loginEnviando: "Enviando código…",
    trocarEmail: "Usar outro e-mail",
    sair: "Sair",
    cadastroTitulo: "Cadastro de afiliado",
    cadastroTexto:
      "Só precisamos do seu nome e WhatsApp — o CNPJ é opcional. Depois de aprovado, você recebe um link só seu para divulgar.",
    formNome: "Seu nome",
    formWhatsapp: "WhatsApp",
    formCnpj: "CNPJ (opcional)",
    formCnpjDica: "Só preencha se divulgar como empresa. Pessoa física também pode ser afiliado.",
    enviar: "Enviar cadastro",
    enviando: "Enviando…",
    enviadoOk: "✅ Cadastro recebido! Vamos analisar e avisar por e-mail.",
    cnpjInvalido: "CNPJ inválido — confira os 14 dígitos (ou deixe em branco).",
    falha: "Não foi possível enviar agora. Tente novamente em instantes.",
    statusPendenteTitulo: "⏳ Cadastro em análise",
    statusPendenteTexto: "Avisamos por e-mail assim que aprovarmos — geralmente em até 1 dia útil.",
    statusRecusadoTitulo: "❌ Cadastro não aprovado",
    statusRecusadoTexto: "Em caso de dúvida, fale com a gente: (21) 99732-2464.",
    verificarNovamente: "Verificar novamente",
    admin: {
      titulo: "Pedidos de afiliado",
      texto: "Cadastros pedindo entrada no programa de afiliados — CNPJ é opcional aqui.",
      vazio: "Nenhum pedido de afiliado ainda.",
      aprovar: "Aprovar",
      recusar: "Recusar",
      excluir: "Excluir",
      pendente: "Pendente",
      aprovado: "Aprovado",
      recusadoRotulo: "Recusado",
      semCnpj: "sem CNPJ",
    },
  },
  atendimento: {
    buscaRotulo: "Buscar nas perguntas frequentes",
    buscaPlaceholder: "Ex.: troca, frete, rastreio…",
    nenhuma: (termo: string) =>
      `Nenhuma pergunta encontrada para "${termo}". Fale com a gente pelo WhatsApp.`,
  },
  busca: {
    titulo: "Resultados para",
    placeholder: "Buscar produto, marca ou necessidade",
    nenhum: (termo: string) =>
      `Nenhum resultado para "${termo}". Confira a digitação ou navegue pelas categorias.`,
    sugestoes: "Sugestões",
    verTodos: "Ver todos os resultados",
  },
  conta: {
    titulo: "Minha conta",
    entrar: "Entrar",
    entrarTitulo: "Entrar na sua conta",
    criarConta: "Criar conta",
    criarTitulo: "Criar sua conta",
    email: "E-mail",
    senha: "Senha",
    senhaDica: "Mínimo de 8 caracteres",
    nome: "Nome completo",
    cep: "CEP",
    numero: "Número da residência",
    complemento: "Complemento (opcional)",
    botaoEntrar: "Entrar",
    botaoEntrando: "Enviando código…",
    botaoCriar: "Criar conta",
    botaoCriando: "Criando conta…",
    botaoConfirmando: "Confirmando…",
    aguardeServidor: "Conectando ao servidor — a primeira vez do dia pode levar até 1 minuto.",
    entrarComGoogle: "Entrar com o Google",
    ou: "ou",
    aindaSemConta: "Ainda não tem conta?",
    jaTemConta: "Já tem conta?",
    codigoTitulo: "Confirme que é você",
    codigoTexto: (email: string) =>
      `Enviamos um código de 6 dígitos para ${email}. Digite-o abaixo para concluir o login.`,
    codigoRotulo: "Código de verificação",
    codigoBotao: "Confirmar código",
    codigoVoltar: "Voltar e tentar outro e-mail",
    codigoEnviado: "✅ Código enviado! Confira sua caixa de entrada (e o spam).",
    codigoReenviado: "✅ Novo código enviado! Confira sua caixa de entrada (e o spam).",
    codigoNaoEnviado: "❌ Não foi possível enviar o código.",
    codigoReenviar: "Reenviar código",
    codigoReenviando: "Reenviando…",
    codigoReenviarEm: (s: number) => `Reenviar código em ${s}s`,
    codigoDemoAviso:
      "Modo demonstração: sem servidor de e-mail, o código aparece aqui. Na versão final ele chega na sua caixa de entrada.",
    codigoDemoRotulo: "Seu código",
    ola: (nome: string) => `Olá, ${nome.split(" ")[0]}!`,
    favoritos: "Meus favoritos",
    favoritosVazio: "Você ainda não favoritou nenhum produto. Toque no coração dos produtos que amar.",
    favoritar: "Adicionar aos favoritos",
    desfavoritar: "Remover dos favoritos",
    meusDados: "Meus dados",
    endereco: "Endereço",
    semEndereco: "Nenhum endereço cadastrado.",
    contaGoogle: "Conta conectada via Google",
    sair: "Sair da conta",
    painelAdmin: "Painel do administrador",
    admin: {
      titulo: `Painel ${LOJA.nome}`,
      subtitulo: "Área restrita do administrador.",
      catalogo: "Catálogo",
      produtos: "produtos ativos",
      marcas: "marcas",
      esgotados: "esgotados",
      pedidos: "Pedidos",
      pedidosVazio:
        "Os pedidos reais aparecem aqui quando o site estiver conectado ao painel/ERP via API.",
      cupons: "Cupons",
      cuponsTexto:
        "Crie códigos de desconto para campanhas. O cliente digita o código na sacola e o desconto entra antes do Pix.",
      cupomCodigo: "Código",
      cupomTipo: "Tipo",
      cupomPercentual: "Percentual (%)",
      cupomValorFixo: "Valor fixo (R$)",
      cupomValor: "Valor",
      cupomMinimo: "Pedido mínimo (R$)",
      cupomAtivo: "Ativo",
      cupomInativo: "Inativo",
      cupomCriar: "Criar cupom",
      cupomExcluir: "Excluir",
      cupomVazio: "Nenhum cupom cadastrado ainda.",
      clientes: "Contas de cliente",
      clientesTexto: (n: number) =>
        n === 1 ? "1 conta criada nesta demonstração." : `${n} contas criadas nesta demonstração.`,
      acessoNegado: "Esta área é restrita. Entre com a conta de administrador.",
    },
  },
} as const;
