// Curriculo de ARABE (padrao moderno). Respostas aceitam o script arabe OU a transliteracao.
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const AR_UNITS: Unit[] = [
  unit('u1', 'أول لقاء', 'Os primeiros 5 minutos', 'A1', '#9BC53D', [
    lesson('u1l1', '👋', 'Cumprimentos', 'Oi, prazer e tchau',
      { title: 'Escreve-se da direita para a esquerda', body: 'O árabe se le da direita para a esquerda e as vogais curtas não aparecem escritas. Por isso aqui você sempre tem a transliteracao: pode responder nela.' },
      [
        ['مرحبا', 'Olá.', undefined, undefined, 'marhaban'],
        ['السلام عليكم', 'A paz esteja com você. (saudação padrão)', 'A resposta é وعليكم السلام (wa alaykum as-salam).', undefined, 'as-salamu alaykum'],
        ['كيف حالك؟', 'Como você está?', undefined, undefined, 'kayfa haluk'],
        ['أنا بخير، شكرا.', 'Estou bem, obrigada.', undefined, undefined, 'ana bikhayr, shukran'],
        ['ما اسمك؟', 'Qual é o seu nome?', undefined, undefined, 'ma ismuk'],
        ['اسمي آنا.', 'Meu nome é Ana.', undefined, undefined, 'ismi ana'],
        ['إلى اللقاء', 'Até logo.', undefined, undefined, 'ila al-liqaa'],
        ['صباح الخير', 'Bom dia.', 'Resposta clássica: صباح النور (sabah an-nur).', undefined, 'sabah al-khayr'],
      ]),
    lesson('u1l2', '🪪', 'Quem é você', 'Se apresentar', undefined,
      [
        ['عمري ستة عشر سنة.', 'Eu tenho dezesseis anos.', 'Literal: "minha idade é 16 anos".', undefined, 'umri sittata ashara sana'],
        ['أنا من البرازيل.', 'Eu sou do Brasil.', undefined, undefined, 'ana min al-brazil'],
        ['أسكن في ساو باولو.', 'Eu moro em São Paulo.', undefined, undefined, 'askunu fi sao paulo'],
        ['أنا طالبة.', 'Eu sou estudante. (mulher)', 'O ـة final marca o feminino.', undefined, 'ana taliba'],
        ['عندي أخوان.', 'Eu tenho dois irmãos.', undefined, undefined, 'indi akhawan'],
        ['هذا صديقي لوكاس.', 'Esse é meu amigo Lucas.', undefined, undefined, 'hadha sadiqi lucas'],
        ['لا أتكلم العربية جيدا بعد.', 'Ainda não falo árabe bem.', undefined, undefined, 'la atakallam al-arabiya jayyidan baad'],
        ['من فضلك، أعد.', 'Por favor, repita.', undefined, undefined, 'min fadlik, aid'],
      ]),
    lesson('u1l3', '❓', 'Perguntas que salvam', 'Destravar a conversa', undefined,
      [
        ['كيف تقول هذا بالعربية؟', 'Como se diz isso em árabe?', undefined, undefined, 'kayfa taqul hadha bil-arabiya'],
        ['ماذا يعني هذا؟', 'O que isso significa?', undefined, undefined, 'madha yani hadha'],
        ['تكلم ببطء من فضلك.', 'Fale devagar, por favor.', undefined, undefined, 'takallam bibut min fadlik'],
        ['آسفة، لم أفهم.', 'Desculpa, não entendi.', undefined, undefined, 'asifa, lam afham'],
        ['هل تتكلم البرتغالية؟', 'Você fala português?', 'هل abre pergunta de sim/não.', undefined, 'hal tatakallam al-burtughaliya'],
        ['من أين أنت؟', 'De onde você é?', undefined, undefined, 'min ayna anta'],
        ['ماذا تعمل؟', 'O que você faz?', undefined, undefined, 'madha tamal'],
        ['لماذا تسأل؟', 'Por que você pergunta?', undefined, undefined, 'limadha tasal'],
      ]),
  ]),
  unit('u2', 'كل يوم', 'Rotina, comida e horas', 'A1', '#4ECDC4', [
    lesson('u2l1', '⏰', 'Números e horas', 'Hora, preço, telefone', undefined,
      [
        ['كم الساعة؟', 'Que horas são?', undefined, undefined, 'kam as-saa'],
        ['الساعة السابعة والنصف.', 'São sete e meia.', undefined, undefined, 'as-saa as-sabia wan-nisf'],
        ['الدرس يبدأ الساعة الثامنة.', 'A aula começa às oito.', undefined, undefined, 'ad-dars yabda as-saa ath-thamina'],
        ['بكم هذا؟', 'Quanto custa isso?', undefined, undefined, 'bikam hadha'],
        ['عشرون ريالا.', 'Vinte riais.', undefined, undefined, 'ishrun riyalan'],
        ['آسفة، تأخرت.', 'Desculpa, me atrasei.', undefined, undefined, 'asifa, taakhkhart'],
        ['نلتقي الساعة السادسة والنصف.', 'A gente se encontra às seis e meia.', undefined, undefined, 'naltaqi as-saa as-sadisa wan-nisf'],
        ['رقم هاتفي هو...', 'Meu número de telefone é...', undefined, undefined, 'raqm hatifi huwa'],
      ]),
    lesson('u2l2', '🍽️', 'No restaurante', 'Pedir comida', undefined,
      [
        ['قهوة من فضلك.', 'Um café, por favor.', undefined, undefined, 'qahwa min fadlik'],
        ['القائمة من فضلك.', 'O cardápio, por favor.', undefined, undefined, 'al-qaima min fadlik'],
        ['أنا جائعة.', 'Estou com fome.', undefined, undefined, 'ana jaia'],
        ['هل هذا حار؟', 'Isso é apimentado?', undefined, undefined, 'hal hadha harr'],
        ['لا آكل اللحم.', 'Eu não como carne.', undefined, undefined, 'la akul al-lahm'],
        ['الحساب من فضلك.', 'A conta, por favor.', undefined, undefined, 'al-hisab min fadlik'],
        ['كان لذيذا، شكرا.', 'Estava delicioso, obrigada.', undefined, undefined, 'kana ladhidhan, shukran'],
        ['للخارج من فضلك.', 'Para viagem, por favor.', undefined, undefined, 'lil-kharij min fadlik'],
      ]),
    lesson('u2l3', '🔁', 'Minha rotina', 'O dia inteiro', undefined,
      [
        ['أستيقظ الساعة السابعة.', 'Eu acordo às sete.', undefined, undefined, 'astayqizu as-saa as-sabia'],
        ['هي تعمل من البيت.', 'Ela trabalha de casa.', undefined, undefined, 'hiya tamal min al-bayt'],
        ['هو يدرس العربية في المساء.', 'Ele estuda árabe à noite.', undefined, undefined, 'huwa yadrus al-arabiya fil-masa'],
        ['أشرب القهوة في الصباح.', 'Eu tomo café de manhã.', undefined, undefined, 'ashrab al-qahwa fis-sabah'],
        ['لا نخرج يوم الاثنين.', 'A gente não sai na segunda.', undefined, undefined, 'la nakhruj yawm al-ithnayn'],
        ['أخي يكره الاستيقاظ مبكرا.', 'Meu irmão odeia acordar cedo.', undefined, undefined, 'akhi yakrah al-istiqadh mubakkiran'],
        ['متى تنام؟', 'Quando você dorme?', undefined, undefined, 'mata tanam'],
        ['أنا دائما متعبة يوم الأحد.', 'No domingo estou sempre cansada.', undefined, undefined, 'ana daiman mutaaba yawm al-ahad'],
      ]),
  ]),
  unit('u3', 'في الشارع', 'Sair e voltar inteira', 'A2', '#F4A259', [
    lesson('u3l1', '🧭', 'Achar o caminho', 'Direções', undefined,
      [
        ['من فضلك، أين الحمام؟', 'Por favor, onde fica o banheiro?', undefined, undefined, 'min fadlik, ayna al-hammam'],
        ['كيف أصل إلى المحطة؟', 'Como eu chego na estação?', undefined, undefined, 'kayfa asil ila al-mahatta'],
        ['امش مستقيما ثم إلى اليسار.', 'Siga reto e depois à esquerda.', undefined, undefined, 'imshi mustaqiman thumma ila al-yasar'],
        ['إنه بجانب البنك.', 'Fica ao lado do banco.', undefined, undefined, 'innahu bijanib al-bank'],
        ['هل هو بعيد من هنا؟', 'É longe daqui?', undefined, undefined, 'hal huwa baid min huna'],
        ['عشر دقائق سيرا.', 'Dez minutos a pé.', undefined, undefined, 'ashr daqaiq sayran'],
        ['أظن أنني ضللت الطريق.', 'Acho que me perdi.', undefined, undefined, 'azunnu annani dalaltu at-tariq'],
        ['أرني على الخريطة من فضلك.', 'Me mostre no mapa, por favor.', undefined, undefined, 'arini ala al-kharita min fadlik'],
      ]),
    lesson('u3l2', '🛍️', 'Comprando', 'Loja e preço', undefined,
      [
        ['أنا أتفرج فقط.', 'Só estou olhando.', undefined, undefined, 'ana atafarraj faqat'],
        ['هل عندك مقاس أصغر؟', 'Você tem um tamanho menor?', undefined, undefined, 'hal indak maqas asghar'],
        ['هل يمكنني تجربته؟', 'Posso experimentar?', undefined, undefined, 'hal yumkinuni tajribatuh'],
        ['هذا غال جدا.', 'Isso é caro demais.', undefined, undefined, 'hadha ghalin jiddan'],
        ['هل تقبلون البطاقة؟', 'Vocês aceitam cartão?', undefined, undefined, 'hal taqbalun al-bitaqa'],
        ['هل يوجد خصم؟', 'Tem desconto?', undefined, undefined, 'hal yujad khasm'],
        ['أريد أن أرجع هذا.', 'Quero devolver isso.', undefined, undefined, 'urid an urjia hadha'],
        ['إنه لا يناسبني.', 'Não serve em mim.', undefined, undefined, 'innahu la yunasibuni'],
      ]),
    lesson('u3l3', '🆘', 'Socorro', 'Quando dá ruim', undefined,
      [
        ['ساعدني من فضلك!', 'Me ajude, por favor!', undefined, undefined, 'saidni min fadlik'],
        ['فقدت هاتفي.', 'Perdi meu telefone.', undefined, undefined, 'faqadtu hatifi'],
        ['سرقوا محفظتي.', 'Roubaram minha carteira.', undefined, undefined, 'saraqu mihfazati'],
        ['اتصل بالإسعاف!', 'Chame a ambulância!', undefined, undefined, 'ittasil bil-isaaf'],
        ['أشعر بتعب.', 'Estou me sentindo mal.', undefined, undefined, 'ashur bitaab'],
        ['هل توجد صيدلية قريبة؟', 'Tem uma farmácia por perto?', undefined, undefined, 'hal tujad saydaliya qariba'],
        ['عندي حساسية من الفول السوداني.', 'Tenho alergia a amendoim.', undefined, undefined, 'indi hasasiya min al-ful as-sudani'],
        ['هذه حالة طارئة.', 'Isso é uma emergência.', undefined, undefined, 'hadhihi hala taria'],
      ]),
  ]),
]
