// Curriculo de ALEMAO.
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const DE_UNITS: Unit[] = [
  unit('u1', 'Erster Kontakt', 'Os primeiros 5 minutos', 'A1', '#FF6B6B', [
    lesson('u1l1', '👋', 'Hallo!', 'Cumprimentar sem medo',
      { title: 'Du x Sie', body: 'DU com amigos, colegas jovens, família. SIE (sempre com S maiúsculo) com desconhecidos e no trabalho. Substantivos em alemão SEMPRE comecam com maiuscula.' },
      [
        ['Hallo, wie geht es dir?', 'Oi, como você está?', undefined, 'Hallo, wie gehts dir?'],
        ['Mir geht es gut, danke. Und dir?', 'Estou bem, obrigada. E você?'],
        ['Freut mich.', 'Prazer em te conhecer.'],
        ['Wie heißt du?', 'Qual é o seu nome?', 'ß soa como ss.', 'Wie heisst du?'],
        ['Ich heiße Ana.', 'Meu nome é Ana.', undefined, 'Ich heisse Ana'],
        ['Bis später!', 'Até mais tarde!'],
        ['Guten Morgen zusammen.', 'Bom dia, pessoal.'],
        ['Schönen Tag noch!', 'Tenha um bom dia!'],
      ]),
    lesson('u1l2', '🪪', 'Wer bist du?', 'Falar de si mesma',
      { title: 'Verbo na posição 2', body: 'Em alemão o verbo conjugado fica SEMPRE na segunda posição da frase: "Heute gehe ich ins Kino" (Hoje VOU eu ao cinema). Estranho, mas e a regra de ouro.' },
      [
        ['Ich bin sechzehn Jahre alt.', 'Eu tenho dezesseis anos.', 'Idade com SEIN (ser), igual ao inglês.'],
        ['Ich komme aus Brasilien.', 'Eu sou do Brasil.'],
        ['Ich wohne in São Paulo.', 'Eu moro em São Paulo.'],
        ['Ich bin Studentin.', 'Eu sou estudante.', 'Profissao sem artigo; feminino ganha -in.'],
        ['Ich habe zwei Brüder.', 'Eu tenho dois irmãos.', undefined, 'Ich habe zwei Brueder'],
        ['Das ist mein Freund Lucas.', 'Esse é meu amigo Lucas.'],
        ['Ich spreche noch nicht gut Deutsch.', 'Ainda não falo bem alemão.'],
        ['Kannst du das wiederholen, bitte?', 'Você pode repetir, por favor?'],
      ]),
    lesson('u1l3', '❓', 'Wichtige Fragen', 'As perguntas essenciais', undefined,
      [
        ['Woher kommst du?', 'De onde você é?'],
        ['Was machst du beruflich?', 'O que você faz da vida?'],
        ['Sprichst du Portugiesisch?', 'Você fala português?'],
        ['Wie sagt man das auf Deutsch?', 'Como se diz isso em alemão?'],
        ['Was bedeutet dieses Wort?', 'O que essa palavra significa?'],
        ['Entschuldigung, ich habe nicht verstanden.', 'Desculpa, não entendi.'],
        ['Kannst du langsamer sprechen?', 'Pode falar mais devagar?'],
        ['Warum fragst du?', 'Por que você pergunta?'],
      ]),
  ]),
  unit('u2', 'Alltag', 'Rotina, comida e horas', 'A1', '#5BC0EB', [
    lesson('u2l1', '⏰', 'Zahlen und Uhrzeit', 'Hora, preço e número', undefined,
      [
        ['Wie spät ist es?', 'Que horas são?', undefined, 'Wie spaet ist es?'],
        ['Es ist halb acht.', 'São sete e meia.', 'ATENÇÃO: "halb acht" = meia PARA as oito = 7h30.'],
        ['Der Unterricht beginnt um acht.', 'A aula começa às oito.'],
        ['Wie viel kostet das?', 'Quanto custa?'],
        ['Das macht zwanzig Euro.', 'Dá vinte euros.'],
        ['Ich bin zu spät, Entschuldigung.', 'Estou atrasada, desculpa.', undefined, 'Ich bin zu spaet, Entschuldigung'],
        ['Wir sehen uns um halb sieben.', 'A gente se vê às seis e meia.'],
        ['Meine Nummer ist null, eins, sieben.', 'Meu número é zero, um, sete.'],
      ]),
    lesson('u2l2', '🥨', 'Im Restaurant', 'Pedir e pagar', undefined,
      [
        ['Ich hätte gern einen Kaffee, bitte.', 'Eu queria um café, por favor.', 'hätte gern = versao educada de will.', 'Ich haette gern einen Kaffee, bitte'],
        ['Die Speisekarte, bitte.', 'O cardápio, por favor.'],
        ['Ich habe Hunger.', 'Estou com fome.'],
        ['Ist das scharf?', 'É apimentado?'],
        ['Ich esse kein Fleisch.', 'Eu não como carne.', 'kein nega substantivo; nicht nega verbo.'],
        ['Die Rechnung, bitte.', 'A conta, por favor.'],
        ['Es war lecker, danke.', 'Estava delicioso, obrigada.'],
        ['Zum Mitnehmen, bitte.', 'Para viagem, por favor.'],
      ]),
    lesson('u2l3', '🔁', 'Mein Alltag', 'O dia inteiro', undefined,
      [
        ['Ich stehe um sieben auf.', 'Eu levanto às sete.', 'aufstehen se parte: stehe ... auf.'],
        ['Sie arbeitet von zu Hause.', 'Ela trabalha de casa.'],
        ['Er lernt abends Deutsch.', 'Ele estuda alemão à noite.', 'lernen = estudar/aprender; studieren = cursar faculdade.'],
        ['Ich frühstücke immer Kaffee.', 'Eu sempre tomo café no café da manhã.', undefined, 'Ich fruehstuecke immer Kaffee'],
        ['Wir gehen montags nie aus.', 'A gente nunca sai às segundas.'],
        ['Mein Bruder hasst früh aufstehen.', 'Meu irmão odeia acordar cedo.', undefined, 'Mein Bruder hasst frueh aufstehen'],
        ['Wann gehst du ins Bett?', 'Que horas você vai dormir?'],
        ['Sonntags bin ich immer müde.', 'Aos domingos estou sempre cansada.', undefined, 'Sonntags bin ich immer muede'],
      ]),
  ]),
  unit('u3', 'Auf der Straße', 'Sair e voltar inteira', 'A2', '#9BC53D', [
    lesson('u3l1', '🧭', 'Den Weg finden', 'Direções', undefined,
      [
        ['Entschuldigung, wo ist die Toilette?', 'Com licença, onde fica o banheiro?'],
        ['Wie komme ich zum Bahnhof?', 'Como eu chego na estação?'],
        ['Gehen Sie geradeaus und dann links.', 'Siga reto e depois à esquerda.'],
        ['Es ist an der Ecke, neben der Bank.', 'Fica na esquina, ao lado do banco.'],
        ['Ist das weit von hier?', 'É longe daqui?'],
        ['Das sind zehn Minuten zu Fuß.', 'São dez minutos a pé.', undefined, 'Das sind zehn Minuten zu Fuss'],
        ['Ich glaube, ich habe mich verlaufen.', 'Acho que me perdi.'],
        ['Können Sie es mir auf der Karte zeigen?', 'Pode me mostrar no mapa?', undefined, 'Koennen Sie es mir auf der Karte zeigen?'],
      ]),
    lesson('u3l2', '🛍️', 'Einkaufen', 'Comprar e devolver', undefined,
      [
        ['Ich schaue mich nur um, danke.', 'Só estou olhando, obrigada.'],
        ['Haben Sie das eine Nummer kleiner?', 'Tem um número menor?'],
        ['Kann ich das anprobieren?', 'Posso experimentar?'],
        ['Das ist zu teuer.', 'É caro demais.'],
        ['Nehmen Sie Karte?', 'Aceitam cartão?'],
        ['Gibt es einen Rabatt?', 'Tem desconto?'],
        ['Ich möchte das zurückgeben.', 'Eu queria devolver isso.', undefined, 'Ich moechte das zurueckgeben'],
        ['Das passt mir nicht.', 'Não serve em mim.'],
      ]),
    lesson('u3l3', '🆘', 'Hilfe!', 'Quando dá ruim', undefined,
      [
        ['Ich brauche Hilfe, bitte.', 'Preciso de ajuda, por favor.'],
        ['Ich habe mein Handy verloren.', 'Perdi meu celular.', 'Celular em alemão é "Handy" — nada a ver com o inglês.'],
        ['Jemand hat meine Geldbörse gestohlen.', 'Alguém roubou minha carteira.', undefined, 'Jemand hat meine Geldboerse gestohlen'],
        ['Rufen Sie einen Krankenwagen!', 'Chame uma ambulância!'],
        ['Mir geht es nicht gut.', 'Não estou me sentindo bem.'],
        ['Gibt es hier eine Apotheke?', 'Tem uma farmácia aqui?'],
        ['Ich bin allergisch gegen Erdnüsse.', 'Sou alérgica a amendoim.', undefined, 'Ich bin allergisch gegen Erdnuesse'],
        ['Das ist ein Notfall.', 'É uma emergência.'],
      ]),
  ]),
]
