// Curriculo de INGLES (A1 -> B1). Cada licao e uma lista de frases; os
// exercicios sao gerados a partir delas, entao a licao nunca cai igual 2x.
import type { Unit } from '../../state/types'
import { lesson } from '../build'

export const EN_UNITS: Unit[] = [
  {
    id: 'u1',
    title: 'Primeiro Contato',
    subtitle: 'Sobreviver aos 5 primeiros minutos de conversa',
    cefr: 'A1',
    color: '#6E8CA8',
    lessons: [
      lesson('u1l1', '👋', 'Oi, tudo bem?', 'Cumprimentar e responder sem travar',
        { title: 'To be (ser/estar)', body: "I am / you are / he is / she is / it is / we are / they are.\nNo dia a dia vira I'm, you're, he's. Em inglês NUNCA se omite o sujeito: \"Esta chovendo\" = \"It is raining\", não \"Is raining\"." },
        [
          ["Hi, how are you?", "Oi, como você esta?", "\"How are you?\" e pergunta social, não exame médico."],
          ["I'm fine, thanks. And you?", "Estou bem, obrigado(a). E você?", undefined, "I am fine, thanks. And you?"],
          ["Nice to meet you.", "Prazer em te conhecer.", "Só se usa no PRIMEIRO encontro."],
          ["What's your name?", "Qual e o seu nome?", undefined, "What is your name?"],
          ["My name is Ana.", "Meu nome é Ana.", undefined, "I'm Ana | I am Ana"],
          ["See you later!", "Até mais tarde!", undefined, "See you!"],
          ["Good morning, everyone.", "Bom dia, pessoal.", "Morning até o almoco, afternoon até ~18h, evening depois."],
          ["Have a good day!", "Tenha um bom dia!"],
        ]),
      lesson('u1l2', '🪪', 'Quem é você', 'Falar de si mesma sem soar um robo', 
        { title: "Have x Be", body: "Idade em inglês usa TO BE: \"I am 15 years old\". \"I have 15 years\" não existe — isso é tradução direta do português e o Grimm vai rir de você." },
        [
          ["I'm 16 years old.", "Eu tenho 16 anos.", "Idade: I AM, nunca I have.", "I am 16 years old | I'm 16"],
          ["I'm from Brazil.", "Eu sou do Brasil.", undefined, "I am from Brazil"],
          ["I live in Sao Paulo.", "Eu moro em São Paulo.", "live IN cidade/pais, live ON rua, live AT número."],
          ["I'm a student.", "Eu sou estudante.", "Profissao em inglês pede artigo: a student, a teacher.", "I am a student"],
          ["I have two brothers.", "Eu tenho dois irmãos."],
          ["This is my friend, Lucas.", "Esse e meu amigo, Lucas."],
          ["I don't speak English very well yet.", "Eu ainda não falo inglês muito bem.", "\"yet\" vai no fim da frase.", "I do not speak English very well yet"],
          ["Can you repeat that, please?", "Você pode repetir, por favor?", "Sua frase mais útil no mundo real."],
        ]),
      lesson('u1l3', '🔢', 'Números e horas', 'Número, telefone, hora e preço', undefined,
        [
          ["What time is it?", "Que horas são?"],
          ["It's half past seven.", "São sete e meia.", "half past = e meia; quarter past = e quinze.", "It is half past seven | It's seven thirty"],
          ["The class starts at eight.", "A aula começa às oito.", "Horario sempre com AT."],
          ["My phone number is nine, nine, four...", "Meu número e nove, nove, quatro...", "Numero de telefone se fala digito por digito."],
          ["How much is it?", "Quanto custa?", undefined, "How much does it cost?"],
          ["It's twenty reais.", "São vinte reais.", undefined, "It is twenty reais"],
          ["I'm late, sorry.", "Estou atrasada, desculpa.", undefined, "I am late, sorry"],
          ["See you at six thirty.", "Te vejo às seis e meia."],
        ]),
      lesson('u1l4', '❓', 'Perguntar sem medo', 'As perguntas que destravam qualquer conversa',
        { title: 'Do / Does', body: "Pergunta no presente pede DO (I/you/we/they) ou DOES (he/she/it) na frente, e o verbo volta pro infinitivo:\n\"Do you like pizza?\" / \"Does she work here?\" (não \"Does she works\")." },
        [
          ["Where are you from?", "De onde você e?"],
          ["What do you do?", "O que você faz (da vida)?", "Não e \"o que você esta fazendo\" — isso e \"What are you doing?\"."],
          ["Do you speak Portuguese?", "Você fala português?"],
          ["How do you say this in English?", "Como se diz isso em inglês?", "Frase de ouro pra não travar."],
          ["What does this word mean?", "O que essa palavra significa?", "Com DOES o verbo fica no infinitivo: mean, não means."],
          ["Sorry, I didn't understand.", "Desculpa, eu não entendi.", undefined, "Sorry, I did not understand"],
          ["Can you speak more slowly, please?", "Você pode falar mais devagar, por favor?"],
          ["Why do you ask?", "Por que você pergunta?"],
        ]),
    ],
  },
  {
    id: 'u2',
    title: 'Dia a Dia',
    subtitle: 'Rotina, família, comida e as mentiras que a gente conta',
    cefr: 'A1',
    color: '#B8F000',
    lessons: [
      lesson('u2l1', '⏰', 'Minha rotina', 'Present simple sem esquecer o -s',
        { title: 'O -s da terceira pessoa', body: "he / she / it ganham -s no presente: she works, he studies, it rains.\nEsquecer esse -s e o erro número 1 de brasileiro. O Grimm conta cada um." },
        [
          ["I wake up at seven every day.", "Eu acordo às sete todo dia."],
          ["She works from home.", "Ela trabalha de casa.", "she workS — terceira pessoa leva -s."],
          ["He studies English at night.", "Ele estuda inglês à noite.", "study -> studies (consoante + y vira ies)."],
          ["I usually have coffee for breakfast.", "Eu geralmente tomo café no café da manhã.", "\"have\" serve pra comer e beber."],
          ["We never go out on Mondays.", "Nos nunca saimos às segundas.", "Com never a frase já e negativa: não use don't."],
          ["My brother doesn't like waking up early.", "Meu irmão não gosta de acordar cedo.", undefined, "My brother does not like waking up early"],
          ["What time do you go to bed?", "Que horas você vai dormir?"],
          ["I'm always tired on Sunday night.", "Eu estou sempre cansada no domingo à noite.", undefined, "I am always tired on Sunday night"],
        ]),
      lesson('u2l2', '👨‍👩‍👧', 'Família e gente', 'Falar dos outros (e reclamar deles)', undefined,
        [
          ["This is my mom.", "Essa e minha mãe.", undefined, "This is my mother"],
          ["My sister is older than me.", "Minha irma e mais velha que eu.", "Adjetivo curto + -er + than."],
          ["We look alike.", "A gente e parecido."],
          ["My parents are very strict.", "Meus pais são muito rígidos."],
          ["He's my best friend since childhood.", "Ele e meu melhor amigo desde a infância.", undefined, "He is my best friend since childhood"],
          ["She has curly hair and green eyes.", "Ela tem cabelo cacheado e olhos verdes."],
          ["My cousin lives abroad.", "Meu primo mora no exterior."],
          ["People are complicated.", "As pessoas são complicadas.", "\"people\" e plural: people ARE, nunca people is."],
        ]),
      lesson('u2l3', '🍔', 'Pedindo comida', 'Restaurante, lanchonete e café', 
        { title: "I'd like", body: "\"I want\" soa grosseiro pedindo algo. Use \"I'd like\" (I would like) — educado e universal." },
        [
          ["I'd like a coffee, please.", "Eu queria um café, por favor.", "I'd like = versao educada de I want.", "I would like a coffee, please"],
          ["Can I have the menu?", "Posso ver o cardápio?"],
          ["I'm hungry.", "Estou com fome.", "Fome e sede usam TO BE: I am hungry / I am thirsty.", "I am hungry"],
          ["Is this spicy?", "Isso e apimentado?"],
          ["I don't eat meat.", "Eu não como carne.", undefined, "I do not eat meat"],
          ["The bill, please.", "A conta, por favor.", "Nos EUA: \"the check, please\".", "Check, please"],
          ["It was delicious, thank you.", "Estava delicioso, obrigada."],
          ["Can I get this to go?", "Posso levar pra viagem?"],
        ]),
      lesson('u2l4', '🏠', 'Em casa agora', 'Present continuous: o que está rolando',
        { title: 'Present continuous', body: "Acontecendo AGORA: be + verbo-ING. \"I am watching a series.\"\nNao use com verbos de estado: \"I am liking\" não — e \"I like\"." },
        [
          ["I'm watching a series.", "Estou assistindo uma serie.", undefined, "I am watching a series"],
          ["She's cooking dinner right now.", "Ela esta cozinhando o jantar agora.", undefined, "She is cooking dinner right now"],
          ["They're not listening to me.", "Eles não estão me escutando.", undefined, "They are not listening to me"],
          ["What are you doing?", "O que você esta fazendo?"],
          ["I'm studying for a test.", "Estou estudando para uma prova.", undefined, "I am studying for a test"],
          ["It's raining again.", "Esta chovendo de novo.", "Precisa do IT: nunca comece com \"Is raining\".", "It is raining again"],
          ["Nobody is answering the phone.", "Ninguém esta atendendo o telefone."],
          ["I'm getting tired of this.", "Estou ficando cansada disso.", undefined, "I am getting tired of this"],
        ]),
    ],
  },
  {
    id: 'u3',
    title: 'Na Rua',
    subtitle: 'Sair de casa e voltar inteira',
    cefr: 'A2',
    color: '#FFB200',
    lessons: [
      lesson('u3l1', '🧭', 'Achar o caminho', 'Pedir e entender direções',
        { title: 'Preposições de lugar', body: "in front of (em frente), next to (ao lado), across from (do outro lado), between (entre), on the corner (na esquina)." },
        [
          ["Excuse me, where is the bathroom?", "Com licenca, onde fica o banheiro?", "\"Excuse me\" abre; \"Sorry\" pede desculpa."],
          ["How do I get to the station?", "Como eu chego na estação?"],
          ["Go straight and turn left.", "Siga reto e vire à esquerda."],
          ["It's on the corner, next to the bank.", "Fica na esquina, do lado do banco.", undefined, "It is on the corner, next to the bank"],
          ["Is it far from here?", "E longe daqui?"],
          ["It's a ten-minute walk.", "Da uns dez minutos a pe.", "ten-minute no singular quando vira adjetivo.", "It is a ten-minute walk"],
          ["I think I'm lost.", "Acho que estou perdida.", undefined, "I think I am lost"],
          ["Can you show me on the map?", "Você pode me mostrar no mapa?"],
        ]),
      lesson('u3l2', '🛍️', 'Comprando', 'Loja, tamanho, preço e devolução', undefined,
        [
          ["I'm just looking, thanks.", "Só estou olhando, obrigada.", undefined, "I am just looking, thanks"],
          ["Do you have this in a smaller size?", "Você tem isso num tamanho menor?"],
          ["Can I try it on?", "Posso experimentar?"],
          ["It's too expensive.", "Esta caro demais.", "too = demais (ruim); very = muito.", "It is too expensive"],
          ["Do you accept card?", "Vocês aceitam cartão?"],
          ["Is there a discount?", "Tem desconto?"],
          ["I'd like to return this.", "Eu gostaria de devolver isso.", undefined, "I would like to return this"],
          ["It doesn't fit me.", "Não serve em mim.", undefined, "It does not fit me"],
        ]),
      lesson('u3l3', '✈️', 'Aeroporto e transporte', 'Chegar, embarcar, não surtar', undefined,
        [
          ["Where is the check-in counter?", "Onde fica o balcao de check-in?"],
          ["I have one bag to check.", "Tenho uma mala pra despachar."],
          ["What's the gate number?", "Qual e o número do portao?", undefined, "What is the gate number?"],
          ["My flight is delayed.", "Meu voo esta atrasado."],
          ["I missed my connection.", "Perdi minha conexão.", "\"lost\" não serve pra voo perdido — e missed."],
          ["Does this bus go downtown?", "Esse ônibus vai pro centro?"],
          ["How much is a ticket to the airport?", "Quanto custa uma passagem pro aeroporto?"],
          ["I'm here on vacation.", "Estou aqui de férias.", "vacation (EUA) / holiday (UK).", "I am here on vacation"],
        ]),
      lesson('u3l4', '🆘', 'Deu ruim', 'Pedir ajuda quando algo dá errado', undefined,
        [
          ["I need help, please.", "Preciso de ajuda, por favor."],
          ["I lost my phone.", "Perdi meu celular."],
          ["Someone stole my wallet.", "Alguém roubou minha carteira."],
          ["Call an ambulance!", "Chame uma ambulância!"],
          ["I don't feel well.", "Não estou me sentindo bem.", undefined, "I do not feel well"],
          ["Is there a pharmacy near here?", "Tem uma farmácia perto daqui?"],
          ["I'm allergic to peanuts.", "Sou alérgica a amendoim.", undefined, "I am allergic to peanuts"],
          ["Can I use your phone? It's an emergency.", "Posso usar seu telefone? E uma emergência."],
        ]),
    ],
  },
  {
    id: 'u4',
    title: 'Ontem',
    subtitle: 'Contar o que aconteceu sem enrolar',
    cefr: 'A2',
    color: '#8A8F98',
    lessons: [
      lesson('u4l1', '⏪', 'Passado simples', 'O -ed e os verbos rebeldes',
        { title: 'Past simple', body: "Regulares ganham -ed: worked, studied, played.\nIrregulares decoram: go->went, have->had, see->saw, eat->até, buy->bought.\nNa negativa e na pergunta o verbo VOLTA ao normal: \"I didn't go\", não \"I didn't went\"." },
        [
          ["I watched a movie last night.", "Eu assisti um filme ontem à noite."],
          ["She went to the beach yesterday.", "Ela foi à praia ontem.", "go -> went."],
          ["We had a great time.", "A gente se divertiu muito.", "have -> had."],
          ["I didn't sleep well.", "Eu não dormi bem.", "Com didn't o verbo fica no infinitivo: sleep, não slept.", "I did not sleep well"],
          ["Did you see that?", "Você viu aquilo?"],
          ["He bought a new bike.", "Ele comprou uma bicicleta nova."],
          ["It was really funny.", "Foi muito engraçado.", "funny = engraçado; fun = divertido."],
          ["They didn't tell me anything.", "Eles não me contaram nada.", undefined, "They did not tell me anything"],
        ]),
      lesson('u4l2', '🎉', 'Como foi o fim de semana', 'Narrar em 3 frases', undefined,
        [
          ["How was your weekend?", "Como foi seu fim de semana?"],
          ["It was pretty chill.", "Foi bem tranquilo.", "chill aqui e giria: tranquilo."],
          ["I stayed home and did nothing.", "Fiquei em casa e não fiz nada."],
          ["We went out on Saturday night.", "A gente saiu no sábado à noite."],
          ["The party was amazing.", "A festa estava incrível."],
          ["I slept until noon.", "Dormi até meio-dia."],
          ["Nothing special happened.", "Nada de especial aconteceu."],
          ["I wish I could do it again.", "Queria poder fazer de novo."],
        ]),
      lesson('u4l3', '📖', 'Contando uma história', 'Ligar as frases: then, so, but', 
        { title: 'Conectores', body: "then (então/depois), só (então/por isso), because (porque), but (mas), after that (depois disso), suddenly (de repente). Sem conector, sua história soa como lista de compras." },
        [
          ["First, we met at the mall.", "Primeiro, a gente se encontrou no shopping."],
          ["Then it started to rain.", "Ai começou a chover."],
          ["So we ran to the car.", "Então a gente correu pro carro."],
          ["But I forgot my keys inside.", "Mas eu esqueci minhas chaves dentro."],
          ["After that, everything went wrong.", "Depois disso, tudo deu errado."],
          ["Suddenly, my phone died.", "De repente, meu celular morreu."],
          ["In the end, we laughed about it.", "No fim, a gente riu disso."],
          ["You should have seen her face.", "Você devia ter visto a cara dela."],
        ]),
      lesson('u4l4', '🕵️', 'Perguntando do passado', 'Interrogar sem parecer policial', undefined,
        [
          ["Where did you go?", "Onde você foi?", "did + verbo no infinitivo: go, não went."],
          ["Who were you with?", "Com quem você estava?"],
          ["What did you say?", "O que você disse?"],
          ["Why didn't you call me?", "Por que você não me ligou?", undefined, "Why did not you call me?"],
          ["How long were you there?", "Quanto tempo você ficou la?"],
          ["Did it hurt?", "Doeu?"],
          ["Was it worth it?", "Valeu a pena?"],
          ["When did that happen?", "Quando isso aconteceu?"],
        ]),
    ],
  },
  {
    id: 'u5',
    title: 'Amanhã',
    subtitle: 'Combinar, prometer e depois cancelar',
    cefr: 'A2',
    color: '#E8EAED',
    lessons: [
      lesson('u5l1', '📅', 'Planos', 'going to x will',
        { title: 'going to x will', body: "going to = plano já decidido (\"I'm going to travel in July\").\nwill = decisão na hora / previsao (\"I'll help you\", \"It will rain\")." },
        [
          ["I'm going to travel in July.", "Vou viajar em julho.", undefined, "I am going to travel in July"],
          ["What are you going to do tomorrow?", "O que você vai fazer amanhã?"],
          ["I'll help you with that.", "Eu te ajudo com isso.", "Decisao na hora pede will.", "I will help you with that"],
          ["She won't come, I'm sure.", "Ela não vem, tenho certeza.", undefined, "She will not come, I am sure"],
          ["We're meeting at seven.", "A gente se encontra às sete.", "Present continuous também serve pra plano marcado.", "We are meeting at seven"],
          ["Maybe I'll change my mind.", "Talvez eu mude de ideia.", undefined, "Maybe I will change my mind"],
          ["I promise I won't be late.", "Prometo que não vou me atrasar.", undefined, "I promise I will not be late"],
          ["Let's decide later.", "Vamos decidir depois.", undefined, "Let us decide later"],
        ]),
      lesson('u5l2', '💌', 'Convites', 'Chamar, aceitar e recusar com jeito', undefined,
        [
          ["Do you want to hang out?", "Quer sair?", "hang out = sair/curtir sem compromisso."],
          ["Are you free on Friday?", "Você esta livre na sexta?"],
          ["Sure, sounds good!", "Claro, parece ótimo!"],
          ["I'd love to, but I can't.", "Eu adoraria, mas não posso.", undefined, "I would love to, but I cannot"],
          ["Can we do it another day?", "Podemos fazer outro dia?"],
          ["I'm busy that day.", "Estou ocupada nesse dia.", undefined, "I am busy that day"],
          ["Count me in!", "To dentro!"],
          ["Maybe next time.", "Talvez na próxima."],
        ]),
      lesson('u5l3', '📱', 'Mensagem e telefone', 'Falar sem ver a cara da pessoa', undefined,
        [
          ["Hello, who's calling?", "Alô, quem esta falando?", undefined, "Hello, who is calling?"],
          ["Can you hear me?", "Você esta me ouvindo?", "hear = ouvir; listen = escutar de proposito."],
          ["The signal is bad.", "O sinal esta ruim."],
          ["I'll text you the address.", "Te mando o endereço por mensagem.", undefined, "I will text you the address"],
          ["Sorry, wrong number.", "Desculpa, número errado."],
          ["Call me back later.", "Me liga de volta depois."],
          ["I'll be right there.", "Já estou indo.", undefined, "I will be right there"],
          ["Let me know when you arrive.", "Me avisa quando chegar."],
        ]),
      lesson('u5l4', '🎯', 'Querer e precisar', 'Modal verbs do dia a dia',
        { title: 'Modais', body: "can (consigo/posso), could (poderia), should (deveria), must/have to (tenho que), might (talvez).\nDepois de modal o verbo vem pelado: \"I should go\", nunca \"I should to go\"." },
        [
          ["I have to study tonight.", "Tenho que estudar hoje à noite."],
          ["You should sleep more.", "Você deveria dormir mais.", "should + verbo sem to."],
          ["Can I ask you something?", "Posso te perguntar uma coisa?"],
          ["I might be late.", "Talvez eu me atrase."],
          ["You don't have to answer.", "Você não precisa responder.", undefined, "You do not have to answer"],
          ["We must be careful.", "Precisamos ter cuidado."],
          ["Could you do me a favor?", "Você poderia me fazer um favor?"],
          ["I need to think about it.", "Preciso pensar nisso."],
        ]),
    ],
  },
  {
    id: 'u6',
    title: 'Conversa de Verdade',
    subtitle: 'Opinião, sentimento, gíria e internet',
    cefr: 'B1',
    color: '#FF2E2E',
    lessons: [
      lesson('u6l1', '💭', 'Dar opinião', 'Concordar, discordar, sem briga', undefined,
        [
          ["In my opinion, that's a bad idea.", "Na minha opinião, isso e uma ma ideia.", undefined, "In my opinion, that is a bad idea"],
          ["I totally agree with you.", "Concordo totalmente com você.", "agree WITH pessoa, agree ON assunto."],
          ["I see your point, but I disagree.", "Entendo seu ponto, mas discordo."],
          ["That doesn't make sense to me.", "Isso não faz sentido pra mim.", undefined, "That does not make sense to me"],
          ["It depends on the situation.", "Depende da situação.", "depend ON, sempre."],
          ["To be honest, I don't care.", "Pra ser sincera, eu não ligo.", undefined, "To be honest, I do not care"],
          ["You have a point there.", "Você tem razão nisso."],
          ["Let's agree to disagree.", "Vamos concordar em discordar."],
        ]),
      lesson('u6l2', '🫀', 'Sentimentos', 'Dizer o que tá rolando por dentro', undefined,
        [
          ["I'm so tired of this.", "Estou tão cansada disso.", undefined, "I am so tired of this"],
          ["That makes me really happy.", "Isso me deixa muito feliz.", "make + pessoa + adjetivo, sem to."],
          ["I'm nervous about the test.", "Estou nervosa por causa da prova.", "nervous ABOUT.", "I am nervous about the test"],
          ["It's not a big deal.", "Não e grande coisa.", undefined, "It is not a big deal"],
          ["I feel like crying.", "Estou com vontade de chorar.", "feel like + verbo-ing = estar com vontade de."],
          ["I'm proud of you.", "Estou orgulhosa de você.", undefined, "I am proud of you"],
          ["That scared me to death.", "Isso me matou de susto."],
          ["I'm over it.", "Já superei.", undefined, "I am over it"],
        ]),
      lesson('u6l3', '🔗', 'Phrasal verbs', 'Os que aparecem em toda série',
        { title: 'Phrasal verbs', body: "Verbo + preposição muda tudo: give up (desistir), figure out (descobrir), show up (aparecer), run out of (ficar sem), put up with (aturar), look forward to (estar ansioso por)." },
        [
          ["Don't give up now.", "Não desista agora.", undefined, "Do not give up now"],
          ["I need to figure this out.", "Preciso descobrir isso."],
          ["He didn't show up.", "Ele não apareceu.", undefined, "He did not show up"],
          ["We ran out of milk.", "A gente ficou sem leite."],
          ["I can't put up with this anymore.", "Não aguento mais isso.", undefined, "I cannot put up with this anymore"],
          ["I'm looking forward to the trip.", "Estou ansiosa pela viagem.", "looking forward TO + substantivo ou verbo-ing.", "I am looking forward to the trip"],
          ["Calm down and think it over.", "Se acalme e pense bem."],
          ["Hold on, I'll be back.", "Espera ai, já volto.", undefined, "Hold on, I will be back"],
        ]),
      lesson('u6l4', '😎', 'Gíria e internet', 'Falar como gente da sua idade', undefined,
        [
          ["That's so cringe.", "Isso e tão vergonha alheia.", undefined, "That is só cringe"],
          ["No way, seriously?", "Sem chance, sério?"],
          ["It's low-key my favorite.", "E meio que meu favorito.", "low-key = meio que, discretamente.", "It is low-key my favorite"],
          ["My bad, I messed up.", "Foi mal, eu pisei na bola."],
          ["I'm dead, that was so funny.", "Eu morri, isso foi engraçado demais.", undefined, "I am dead, that was só funny"],
          ["Spill the tea!", "Conta a fofoca!"],
          ["It slaps.", "E muito bom (música).", "slaps = e muito bom, geralmente sobre música."],
          ["Bet, let's do it.", "Fechou, bora.", undefined, "Bet, let us do it"],
        ]),
    ],
  },
]
