// Curriculo de ESPANHOL.
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const ES_UNITS: Unit[] = [
  unit('u1', 'Primer Contacto', 'Os primeiros 5 minutos de conversa', 'A1', '#FFB200', [
    lesson('u1l1', '👋', 'Hola, ¿qué tal?', 'Cumprimentar e responder',
      { title: 'Ser x Estar', body: 'Igual ao português: SER para o que você e (soy estudiante), ESTAR para estado (estoy cansada). Boa noticia: aqui o português te ajuda.' },
      [
        ['Hola, ¿cómo estás?', 'Oi, como você está?'],
        ['Estoy bien, gracias. ¿Y tú?', 'Estou bem, obrigada. E você?'],
        ['Mucho gusto.', 'Prazer em te conhecer.', 'Literalmente "muito prazer".'],
        ['¿Cómo te llamas?', 'Qual é o seu nome?', 'Literal: "como você se chama".'],
        ['Me llamo Ana.', 'Meu nome é Ana.', undefined, 'Mi nombre es Ana'],
        ['¡Hasta luego!', 'Até mais!', undefined, 'Hasta luego'],
        ['Buenos días a todos.', 'Bom dia a todos.'],
        ['Que tengas un buen día.', 'Tenha um bom dia.'],
      ]),
    lesson('u1l2', '🪪', '¿Quién eres?', 'Falar de si mesma', undefined,
      [
        ['Tengo dieciséis años.', 'Eu tenho dezesseis anos.', 'Idade com TENER, igual em português.'],
        ['Soy de Brasil.', 'Eu sou do Brasil.'],
        ['Vivo en São Paulo.', 'Eu moro em São Paulo.'],
        ['Soy estudiante.', 'Eu sou estudante.', 'Sem artigo: NAO se diz "soy una estudiante".'],
        ['Tengo dos hermanos.', 'Eu tenho dois irmãos.'],
        ['Este es mi amigo Lucas.', 'Esse é meu amigo Lucas.'],
        ['Todavía no hablo bien español.', 'Ainda não falo bem espanhol.', 'todavía = ainda (falso amigo de "todavia").'],
        ['¿Puedes repetir, por favor?', 'Você pode repetir, por favor?'],
      ]),
    lesson('u1l3', '❓', 'Preguntas clave', 'As perguntas que destravam tudo', undefined,
      [
        ['¿De dónde eres?', 'De onde você é?'],
        ['¿A qué te dedicas?', 'O que você faz da vida?'],
        ['¿Hablas portugués?', 'Você fala português?'],
        ['¿Cómo se dice esto en español?', 'Como se diz isso em espanhol?'],
        ['¿Qué significa esta palabra?', 'O que essa palavra significa?'],
        ['Perdón, no entendí.', 'Desculpa, não entendi.'],
        ['¿Puedes hablar más despacio?', 'Você pode falar mais devagar?'],
        ['¿Por qué preguntas?', 'Por que você pergunta?'],
      ]),
  ]),
  unit('u2', 'Día a Día', 'Rotina, comida e horas', 'A1', '#B8F000', [
    lesson('u2l1', '⏰', 'Números y horas', 'Hora, preço e telefone', undefined,
      [
        ['¿Qué hora es?', 'Que horas são?'],
        ['Son las siete y media.', 'São sete e meia.'],
        ['La clase empieza a las ocho.', 'A aula começa às oito.'],
        ['¿Cuánto cuesta?', 'Quanto custa?'],
        ['Son veinte reales.', 'São vinte reais.'],
        ['Llego tarde, perdón.', 'Estou atrasada, desculpa.'],
        ['Nos vemos a las seis y media.', 'A gente se vê às seis e meia.'],
        ['Mi número es nueve, nueve, cuatro.', 'Meu número é nove, nove, quatro.'],
      ]),
    lesson('u2l2', '🍽️', 'En el restaurante', 'Pedir sem apontar pro cardápio', undefined,
      [
        ['Quisiera un café, por favor.', 'Eu queria um café, por favor.', 'quisiera = versao educada de quiero.'],
        ['¿Me trae la carta?', 'Pode trazer o cardápio?', '"carta" aqui é cardápio, não carta.', '¿Me trae el menú?'],
        ['Tengo hambre.', 'Estou com fome.'],
        ['¿Esto pica?', 'Isso é apimentado?', 'picar = arder de pimenta.'],
        ['No como carne.', 'Eu não como carne.'],
        ['La cuenta, por favor.', 'A conta, por favor.'],
        ['Estaba delicioso, gracias.', 'Estava delicioso, obrigada.'],
        ['Para llevar, por favor.', 'Para viagem, por favor.'],
      ]),
    lesson('u2l3', '🔁', 'Mi rutina', 'Verbos reflexivos do dia',
      { title: 'Verbos reflexivos', body: 'me despierto, me levanto, me acuesto. O pronome vem ANTES do verbo conjugado: "me despierto", nunca "despierto me".' },
      [
        ['Me despierto a las siete.', 'Eu acordo às sete.'],
        ['Ella trabaja desde casa.', 'Ela trabalha de casa.'],
        ['Él estudia español por la noche.', 'Ele estuda espanhol à noite.'],
        ['Suelo desayunar café.', 'Eu costumo tomar café da manhã.', 'soler + infinitivo = costumar.'],
        ['Nunca salimos los lunes.', 'A gente nunca sai às segundas.'],
        ['A mi hermano no le gusta madrugar.', 'Meu irmão não gosta de acordar cedo.', 'gustar é invertido: a coisa é que "agrada" a pessoa.'],
        ['¿A qué hora te acuestas?', 'Que horas você vai dormir?'],
        ['Siempre estoy cansada los domingos.', 'Estou sempre cansada aos domingos.'],
      ]),
  ]),
  unit('u3', 'En la Calle', 'Sair de casa e voltar inteira', 'A2', '#6E8CA8', [
    lesson('u3l1', '🧭', 'Cómo llegar', 'Direções e transporte', undefined,
      [
        ['Perdone, ¿dónde está el baño?', 'Com licença, onde fica o banheiro?'],
        ['¿Cómo llego a la estación?', 'Como eu chego na estação?'],
        ['Siga recto y gire a la izquierda.', 'Siga reto e vire à esquerda.'],
        ['Está en la esquina, al lado del banco.', 'Fica na esquina, ao lado do banco.'],
        ['¿Está lejos de aquí?', 'É longe daqui?'],
        ['Son diez minutos a pie.', 'São dez minutos a pé.'],
        ['Creo que estoy perdida.', 'Acho que estou perdida.'],
        ['¿Me lo puede mostrar en el mapa?', 'Pode me mostrar no mapa?'],
      ]),
    lesson('u3l2', '🛍️', 'De compras', 'Loja, tamanho e preço', undefined,
      [
        ['Solo estoy mirando, gracias.', 'Só estou olhando, obrigada.'],
        ['¿Lo tiene en una talla más pequeña?', 'Tem num tamanho menor?', 'talla = tamanho de roupa.'],
        ['¿Me lo puedo probar?', 'Posso experimentar?'],
        ['Es demasiado caro.', 'É caro demais.'],
        ['¿Aceptan tarjeta?', 'Aceitam cartão?'],
        ['¿Hay descuento?', 'Tem desconto?'],
        ['Quisiera devolver esto.', 'Eu gostaria de devolver isso.'],
        ['No me queda bien.', 'Não ficou bom em mim.', 'quedar bien = ficar bem (roupa).'],
      ]),
    lesson('u3l3', '🆘', 'Se armó', 'Pedir ajuda quando dá ruim', undefined,
      [
        ['Necesito ayuda, por favor.', 'Preciso de ajuda, por favor.'],
        ['Perdí mi celular.', 'Perdi meu celular.', undefined, 'Perdí mi móvil'],
        ['Alguien me robó la cartera.', 'Alguém roubou minha carteira.'],
        ['¡Llamen a una ambulancia!', 'Chamem uma ambulância!'],
        ['No me siento bien.', 'Não estou me sentindo bem.'],
        ['¿Hay una farmacia cerca?', 'Tem uma farmácia perto?'],
        ['Soy alérgica al maní.', 'Sou alérgica a amendoim.', undefined, 'Soy alérgica al cacahuete'],
        ['Es una emergencia.', 'É uma emergência.'],
      ]),
  ]),
]
