// Curriculo de FRANCES.
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const FR_UNITS: Unit[] = [
  unit('u1', 'Premier Contact', 'Os primeiros 5 minutos', 'A1', '#6E8CA8', [
    lesson('u1l1', '👋', 'Bonjour !', 'Cumprimentar sem gaguejar',
      { title: 'Tu x Vous', body: 'TU com amigos e família. VOUS com desconhecidos, professores, atendentes — e também plural. Na dúvida, use vous: ninguém se ofende.' },
      [
        ['Bonjour, comment ça va ?', 'Oi, como vai?'],
        ['Ça va bien, merci. Et toi ?', 'Vou bem, obrigada. E você?'],
        ['Enchantée.', 'Prazer em te conhecer.', 'Homem escreve "enchanté"; mulher, "enchantée".'],
        ['Comment tu t’appelles ?', 'Qual é o seu nome?', undefined, "Comment tu t'appelles ?"],
        ['Je m’appelle Ana.', 'Meu nome é Ana.', undefined, "Je m'appelle Ana"],
        ['À plus tard !', 'Até mais tarde!', undefined, 'A plus tard'],
        ['Bonsoir tout le monde.', 'Boa noite, pessoal.', 'bonsoir a partir do fim da tarde.'],
        ['Bonne journée !', 'Tenha um bom dia!'],
      ]),
    lesson('u1l2', '🪪', 'Qui es-tu ?', 'Falar de si mesma', undefined,
      [
        ['J’ai seize ans.', 'Eu tenho dezesseis anos.', 'Idade com AVOIR: j’ai ... ans.', "J'ai seize ans"],
        ['Je viens du Brésil.', 'Eu sou do Brasil.', undefined, 'Je suis brésilienne'],
        ['J’habite à São Paulo.', 'Eu moro em São Paulo.', undefined, "J'habite à São Paulo"],
        ['Je suis étudiante.', 'Eu sou estudante.', 'Profissao sem artigo em francês.'],
        ['J’ai deux frères.', 'Eu tenho dois irmãos.', undefined, "J'ai deux frères"],
        ['Voici mon ami Lucas.', 'Esse é meu amigo Lucas.'],
        ['Je ne parle pas encore bien français.', 'Ainda não falo bem francês.', 'Negativa em duas partes: ne ... pas.'],
        ['Tu peux répéter, s’il te plaît ?', 'Você pode repetir, por favor?', undefined, "Tu peux répéter, s'il te plaît ?"],
      ]),
    lesson('u1l3', '❓', 'Questions clés', 'As perguntas essenciais', undefined,
      [
        ['Tu viens d’où ?', 'De onde você é?', undefined, "Tu viens d'où ? | D'où viens-tu ?"],
        ['Qu’est-ce que tu fais dans la vie ?', 'O que você faz da vida?', undefined, "Qu'est-ce que tu fais dans la vie ?"],
        ['Tu parles portugais ?', 'Você fala português?'],
        ['Comment on dit ça en français ?', 'Como se diz isso em francês?'],
        ['Qu’est-ce que ça veut dire ?', 'O que isso quer dizer?', undefined, "Qu'est-ce que ça veut dire ?"],
        ['Désolée, je n’ai pas compris.', 'Desculpa, não entendi.', undefined, "Désolée, je n'ai pas compris"],
        ['Tu peux parler plus lentement ?', 'Você pode falar mais devagar?'],
        ['Pourquoi tu demandes ?', 'Por que você pergunta?'],
      ]),
  ]),
  unit('u2', 'Au Quotidien', 'Rotina, comida e horas', 'A1', '#8A8F98', [
    lesson('u2l1', '⏰', 'Chiffres et heures', 'Hora, preço e número', undefined,
      [
        ['Quelle heure est-il ?', 'Que horas são?'],
        ['Il est sept heures et demie.', 'São sete e meia.', 'Sempre "il est" para horas.'],
        ['Le cours commence à huit heures.', 'A aula começa às oito.'],
        ['Ça coûte combien ?', 'Quanto custa?', undefined, 'C’est combien ?'],
        ['Ça fait vingt euros.', 'Dá vinte euros.'],
        ['Je suis en retard, désolée.', 'Estou atrasada, desculpa.'],
        ['On se voit à six heures et demie.', 'A gente se vê às seis e meia.'],
        ['Mon numéro, c’est zéro six...', 'Meu número é zero seis...', undefined, "Mon numéro, c'est zéro six..."],
      ]),
    lesson('u2l2', '🥐', 'Au café', 'Pedir comida e bebida', undefined,
      [
        ['Je voudrais un café, s’il vous plaît.', 'Eu queria um café, por favor.', 'je voudrais = versao educada de je veux.', "Je voudrais un café, s'il vous plaît"],
        ['La carte, s’il vous plaît.', 'O cardápio, por favor.', undefined, "La carte, s'il vous plaît"],
        ['J’ai faim.', 'Estou com fome.', undefined, "J'ai faim"],
        ['C’est épicé ?', 'É apimentado?', undefined, "C'est épicé ?"],
        ['Je ne mange pas de viande.', 'Eu não como carne.'],
        ['L’addition, s’il vous plaît.', 'A conta, por favor.', undefined, "L'addition, s'il vous plaît"],
        ['C’était délicieux, merci.', 'Estava delicioso, obrigada.', undefined, "C'était délicieux, merci"],
        ['C’est à emporter.', 'É para viagem.', undefined, "C'est à emporter"],
      ]),
    lesson('u2l3', '🔁', 'Ma routine', 'O dia inteiro em 8 frases', undefined,
      [
        ['Je me réveille à sept heures.', 'Eu acordo às sete.', 'Verbo reflexivo: je me réveille.'],
        ['Elle travaille à la maison.', 'Ela trabalha em casa.'],
        ['Il étudie le français le soir.', 'Ele estuda francês à noite.'],
        ['Je prends un café le matin.', 'Eu tomo um café de manhã.', 'prendre serve para comer e beber.'],
        ['On ne sort jamais le lundi.', 'A gente nunca sai na segunda.', 'ne ... jamais = nunca.'],
        ['Mon frère déteste se lever tôt.', 'Meu irmão odeia acordar cedo.'],
        ['Tu te couches à quelle heure ?', 'Que horas você vai dormir?'],
        ['Je suis toujours fatiguée le dimanche.', 'Estou sempre cansada no domingo.'],
      ]),
  ]),
  unit('u3', 'Dans la Rue', 'Sair e voltar inteira', 'A2', '#FF2E2E', [
    lesson('u3l1', '🧭', 'Trouver son chemin', 'Direções', undefined,
      [
        ['Excusez-moi, où sont les toilettes ?', 'Com licença, onde fica o banheiro?', 'Sempre no plural: les toilettes.'],
        ['Comment je vais à la gare ?', 'Como eu chego na estação?'],
        ['Allez tout droit et tournez à gauche.', 'Siga reto e vire à esquerda.', 'tout droit = reto; à droite = à direita. Cuidado.'],
        ['C’est au coin, à côté de la banque.', 'Fica na esquina, do lado do banco.', undefined, "C'est au coin, à côté de la banque"],
        ['C’est loin d’ici ?', 'É longe daqui?', undefined, "C'est loin d'ici ?"],
        ['C’est à dix minutes à pied.', 'Dá dez minutos a pé.', undefined, "C'est à dix minutes à pied"],
        ['Je crois que je suis perdue.', 'Acho que estou perdida.'],
        ['Vous pouvez me montrer sur la carte ?', 'Pode me mostrar no mapa?'],
      ]),
    lesson('u3l2', '🛍️', 'Faire du shopping', 'Comprar sem pagar caro', undefined,
      [
        ['Je regarde, merci.', 'Só estou olhando, obrigada.'],
        ['Vous l’avez en plus petit ?', 'Tem num tamanho menor?', undefined, "Vous l'avez en plus petit ?"],
        ['Je peux l’essayer ?', 'Posso experimentar?', undefined, "Je peux l'essayer ?"],
        ['C’est trop cher.', 'É caro demais.', undefined, "C'est trop cher"],
        ['Vous acceptez la carte ?', 'Aceitam cartão?'],
        ['Il y a une réduction ?', 'Tem desconto?'],
        ['Je voudrais rendre ça.', 'Eu queria devolver isso.'],
        ['Ça ne me va pas.', 'Não ficou bom em mim.'],
      ]),
    lesson('u3l3', '🆘', 'Au secours', 'Quando dá ruim', undefined,
      [
        ['J’ai besoin d’aide, s’il vous plaît.', 'Preciso de ajuda, por favor.', undefined, "J'ai besoin d'aide, s'il vous plaît"],
        ['J’ai perdu mon téléphone.', 'Perdi meu celular.', undefined, "J'ai perdu mon téléphone"],
        ['On m’a volé mon portefeuille.', 'Roubaram minha carteira.', undefined, "On m'a volé mon portefeuille"],
        ['Appelez une ambulance !', 'Chamem uma ambulância!'],
        ['Je ne me sens pas bien.', 'Não estou me sentindo bem.'],
        ['Il y a une pharmacie près d’ici ?', 'Tem farmácia perto daqui?', undefined, "Il y a une pharmacie près d'ici ?"],
        ['Je suis allergique aux cacahuètes.', 'Sou alérgica a amendoim.'],
        ['C’est une urgence.', 'É uma emergência.', undefined, "C'est une urgence"],
      ]),
  ]),
]
