// Curriculo de ITALIANO.
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const IT_UNITS: Unit[] = [
  unit('u1', 'Primo Contatto', 'Os primeiros 5 minutos', 'A1', '#B8F000', [
    lesson('u1l1', '👋', 'Ciao!', 'Cumprimentar como gente',
      { title: 'Ciao x Salve x Buongiorno', body: 'CIAO só com quem você tem intimidade (serve para oi e tchau). Com desconhecido: buongiorno (dia) ou buonasera (tarde/noite). Salve resolve quando você não sabe.' },
      [
        ['Ciao, come stai?', 'Oi, como você está?'],
        ['Sto bene, grazie. E tu?', 'Estou bem, obrigada. E você?'],
        ['Piacere di conoscerti.', 'Prazer em te conhecer.', undefined, 'Piacere'],
        ['Come ti chiami?', 'Qual é o seu nome?'],
        ['Mi chiamo Ana.', 'Meu nome é Ana.'],
        ['Ci vediamo dopo!', 'A gente se vê depois!'],
        ['Buongiorno a tutti.', 'Bom dia a todos.'],
        ['Buona giornata!', 'Tenha um bom dia!'],
      ]),
    lesson('u1l2', '🪪', 'Chi sei?', 'Falar de si mesma', undefined,
      [
        ['Ho sedici anni.', 'Eu tenho dezesseis anos.', 'Idade com AVERE, igual ao português.'],
        ['Vengo dal Brasile.', 'Eu sou do Brasil.', undefined, 'Sono brasiliana'],
        ['Abito a São Paulo.', 'Eu moro em São Paulo.', 'abitare A cidade, IN pais.'],
        ['Sono una studentessa.', 'Eu sou estudante.', 'No feminino: studentessa.'],
        ['Ho due fratelli.', 'Eu tenho dois irmãos.'],
        ['Questo è il mio amico Lucas.', 'Esse é meu amigo Lucas.'],
        ['Non parlo ancora bene italiano.', 'Ainda não falo bem italiano.'],
        ['Puoi ripetere, per favore?', 'Você pode repetir, por favor?'],
      ]),
    lesson('u1l3', '❓', 'Domande utili', 'As perguntas que salvam', undefined,
      [
        ['Di dove sei?', 'De onde você é?'],
        ['Che lavoro fai?', 'O que você faz da vida?'],
        ['Parli portoghese?', 'Você fala português?'],
        ['Come si dice questo in italiano?', 'Como se diz isso em italiano?'],
        ['Che cosa significa questa parola?', 'O que essa palavra significa?'],
        ['Scusa, non ho capito.', 'Desculpa, não entendi.'],
        ['Puoi parlare più lentamente?', 'Pode falar mais devagar?'],
        ['Perché chiedi?', 'Por que você pergunta?'],
      ]),
  ]),
  unit('u2', 'Ogni Giorno', 'Rotina, comida e horas', 'A1', '#FFB200', [
    lesson('u2l1', '⏰', 'Numeri e ore', 'Hora, preço e número', undefined,
      [
        ['Che ore sono?', 'Que horas são?'],
        ['Sono le sette e mezza.', 'São sete e meia.'],
        ['La lezione comincia alle otto.', 'A aula começa às oito.'],
        ['Quanto costa?', 'Quanto custa?'],
        ['Sono venti euro.', 'São vinte euros.'],
        ['Sono in ritardo, scusa.', 'Estou atrasada, desculpa.'],
        ['Ci vediamo alle sei e mezza.', 'A gente se vê às seis e meia.'],
        ['Il mio número è tre, tre, cinque.', 'Meu número é três, três, cinco.'],
      ]),
    lesson('u2l2', '🍝', 'Al ristorante', 'Comer bem e pagar certo', undefined,
      [
        ['Vorrei un caffè, per favore.', 'Eu queria um café, por favor.', 'vorrei = versao educada de voglio.'],
        ['Mi porta il menù?', 'Pode trazer o cardápio?'],
        ['Ho fame.', 'Estou com fome.'],
        ['È piccante?', 'É apimentado?'],
        ['Non mangio carne.', 'Eu não como carne.'],
        ['Il conto, per favore.', 'A conta, por favor.'],
        ['Era buonissimo, grazie.', 'Estava ótimo, obrigada.'],
        ['Da portare via, per favore.', 'Para viagem, por favor.'],
      ]),
    lesson('u2l3', '🔁', 'La mia routine', 'O dia inteiro', undefined,
      [
        ['Mi sveglio alle sette.', 'Eu acordo às sete.'],
        ['Lei lavora da casa.', 'Ela trabalha de casa.'],
        ['Lui studia italiano la sera.', 'Ele estuda italiano à noite.'],
        ['Faccio colazione con un caffè.', 'Tomo café da manhã com um café.'],
        ['Non usciamo mai il lunedì.', 'A gente nunca sai na segunda.', 'A dupla negativa é obrigatória: non ... mai.'],
        ['A mio fratello non piace alzarsi presto.', 'Meu irmão não gosta de acordar cedo.', 'piacere é invertido, igual ao gustar espanhol.'],
        ['A che ora vai a letto?', 'Que horas você vai dormir?'],
        ['Sono sempre stanca la domenica.', 'Estou sempre cansada no domingo.'],
      ]),
  ]),
  unit('u3', 'In Strada', 'Sair e voltar inteira', 'A2', '#8A8F98', [
    lesson('u3l1', '🧭', 'Trovare la strada', 'Direções', undefined,
      [
        ['Scusi, dov’è il bagno?', 'Com licença, onde fica o banheiro?'],
        ['Come arrivo alla stazione?', 'Como eu chego na estação?'],
        ['Vada dritto e giri a sinistra.', 'Siga reto e vire à esquerda.'],
        ['È all’angolo, accanto alla banca.', 'Fica na esquina, ao lado do banco.'],
        ['È lontano da qui?', 'É longe daqui?'],
        ['Sono dieci minuti a piedi.', 'São dez minutos a pé.'],
        ['Credo di essermi persa.', 'Acho que me perdi.'],
        ['Me lo può mostrare sulla mappa?', 'Pode me mostrar no mapa?'],
      ]),
    lesson('u3l2', '🛍️', 'Fare shopping', 'Comprar e devolver', undefined,
      [
        ['Sto solo guardando, grazie.', 'Só estou olhando, obrigada.'],
        ['Ce l’ha in una taglia più piccola?', 'Tem num tamanho menor?'],
        ['Posso provarlo?', 'Posso experimentar?'],
        ['È troppo caro.', 'É caro demais.'],
        ['Accettate la carta?', 'Aceitam cartão?'],
        ['C’è uno sconto?', 'Tem desconto?'],
        ['Vorrei restituire questo.', 'Eu queria devolver isso.'],
        ['Non mi sta bene.', 'Não ficou bom em mim.'],
      ]),
    lesson('u3l3', '🆘', 'Aiuto!', 'Quando dá ruim', undefined,
      [
        ['Ho bisogno di aiuto, per favore.', 'Preciso de ajuda, por favor.'],
        ['Ho perso il telefono.', 'Perdi meu celular.'],
        ['Mi hanno rubato il portafoglio.', 'Roubaram minha carteira.'],
        ['Chiamate un’ambulanza!', 'Chamem uma ambulância!'],
        ['Non mi sento bene.', 'Não estou me sentindo bem.'],
        ['C’è una farmacia qui vicino?', 'Tem farmácia aqui perto?'],
        ['Sono allergica alle arachidi.', 'Sou alérgica a amendoim.'],
        ['È un’emergenza.', 'É uma emergência.'],
      ]),
  ]),
]
