// Curriculo de JAPONES. Respostas aceitam o script nativo OU o romaji.
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const JA_UNITS: Unit[] = [
  unit('u1', '初めまして', 'Os primeiros 5 minutos', 'A1', '#FF2E2E', [
    lesson('u1l1', '👋', 'Cumprimentos', 'Dizer oi no nível certo de educação',
      { title: 'です é seu escudo', body: 'A terminação です (desu) deixa a frase educada. Entre amigos some, mas com desconhecido NUNCA tire. Ordem da frase: sujeito - objeto - VERBO. O verbo vai sempre no fim.' },
      [
        ['こんにちは。', 'Olá. (durante o dia)', undefined, undefined, 'konnichiwa'],
        ['はじめまして。', 'Muito prazer.', 'Só no primeiro encontro, literalmente "é a primeira vez".', undefined, 'hajimemashite'],
        ['お元気ですか。', 'Como você está?', undefined, undefined, 'ogenki desu ka'],
        ['元気です。ありがとう。', 'Estou bem. Obrigada.', undefined, undefined, 'genki desu. arigatou'],
        ['お名前は何ですか。', 'Qual é o seu nome?', undefined, undefined, 'onamae wa nan desu ka'],
        ['私はアナです。', 'Eu sou a Ana.', 'Nome estrangeiro se escreve em katakana.', undefined, 'watashi wa ana desu'],
        ['またね。', 'Até mais.', 'Informal, com amigos.', undefined, 'mata ne'],
        ['おはようございます。', 'Bom dia.', undefined, undefined, 'ohayou gozaimasu'],
      ]),
    lesson('u1l2', '🪪', 'Quem é você', 'Se apresentar de verdade', undefined,
      [
        ['私は十六歳です。', 'Eu tenho dezesseis anos.', undefined, undefined, 'watashi wa juurokusai desu'],
        ['ブラジルから来ました。', 'Eu vim do Brasil.', 'から = de/desde.', undefined, 'burajiru kara kimashita'],
        ['サンパウロに住んでいます。', 'Eu moro em São Paulo.', undefined, undefined, 'sanpauro ni sundeimasu'],
        ['学生です。', 'Sou estudante.', 'O 私は fica implícito quando já é óbvio.', undefined, 'gakusei desu'],
        ['兄弟が二人います。', 'Eu tenho dois irmãos.', 'います para pessoas/animais, あります para coisas.', undefined, 'kyoudai ga futari imasu'],
        ['こちらは友達のルーカスです。', 'Esse é meu amigo Lucas.', undefined, undefined, 'kochira wa tomodachi no ruukasu desu'],
        ['日本語はまだ下手です。', 'Meu japonês ainda é ruim.', undefined, undefined, 'nihongo wa mada heta desu'],
        ['もう一度お願いします。', 'Mais uma vez, por favor.', undefined, undefined, 'mou ichido onegaishimasu'],
      ]),
    lesson('u1l3', '❓', 'Perguntas que salvam', 'Destravar qualquer conversa',
      { title: 'か transforma em pergunta', body: 'Não existe ponto de interrogação obrigatório: basta por か no fim. 元気です (estou bem) -> 元気ですか (você esta bem?).' },
      [
        ['これは日本語で何と言いますか。', 'Como se diz isso em japonês?', undefined, undefined, 'kore wa nihongo de nan to iimasu ka'],
        ['どういう意味ですか。', 'O que isso significa?', undefined, undefined, 'douiu imi desu ka'],
        ['ゆっくり話してください。', 'Fale devagar, por favor.', 'てください = por favor faça.', undefined, 'yukkuri hanashite kudasai'],
        ['すみません、わかりません。', 'Desculpe, não entendi.', 'すみません serve para desculpa E para chamar atenção.', undefined, 'sumimasen, wakarimasen'],
        ['日本語を話しますか。', 'Você fala japonês?', undefined, undefined, 'nihongo o hanashimasu ka'],
        ['出身はどこですか。', 'De onde você é?', undefined, undefined, 'shusshin wa doko desu ka'],
        ['お仕事は何ですか。', 'O que você faz da vida?', undefined, undefined, 'oshigoto wa nan desu ka'],
        ['大丈夫ですか。', 'Está tudo bem?', undefined, undefined, 'daijoubu desu ka'],
      ]),
  ]),
  unit('u2', '毎日', 'Rotina, comida e horas', 'A1', '#6E8CA8', [
    lesson('u2l1', '⏰', 'Números e horas', 'Hora, preço, telefone', undefined,
      [
        ['今何時ですか。', 'Que horas são?', undefined, undefined, 'ima nanji desu ka'],
        ['七時半です。', 'São sete e meia.', '半 = meia hora.', undefined, 'shichiji han desu'],
        ['授業は八時に始まります。', 'A aula começa às oito.', 'に marca horário.', undefined, 'jugyou wa hachiji ni hajimarimasu'],
        ['いくらですか。', 'Quanto custa?', undefined, undefined, 'ikura desu ka'],
        ['千円です。', 'São mil ienes.', undefined, undefined, 'sen en desu'],
        ['遅れてすみません。', 'Desculpe o atraso.', undefined, undefined, 'okurete sumimasen'],
        ['六時半に会いましょう。', 'Vamos nos encontrar às seis e meia.', 'ましょう = vamos.', undefined, 'rokuji han ni aimashou'],
        ['電話番号を教えてください。', 'Me diga seu telefone, por favor.', undefined, undefined, 'denwa bangou o oshiete kudasai'],
      ]),
    lesson('u2l2', '🍜', 'No restaurante', 'Pedir comida sem apontar', undefined,
      [
        ['コーヒーをください。', 'Um café, por favor.', 'を marca o objeto.', undefined, 'koohii o kudasai'],
        ['メニューをお願いします。', 'O cardápio, por favor.', undefined, undefined, 'menyuu o onegaishimasu'],
        ['お腹が空きました。', 'Estou com fome.', undefined, undefined, 'onaka ga sukimashita'],
        ['辛いですか。', 'É apimentado?', undefined, undefined, 'karai desu ka'],
        ['肉は食べません。', 'Eu não como carne.', 'ません = negativa educada.', undefined, 'niku wa tabemasen'],
        ['お会計をお願いします。', 'A conta, por favor.', undefined, undefined, 'okaikei o onegaishimasu'],
        ['おいしかったです。', 'Estava delicioso.', 'Passado de おいしい.', undefined, 'oishikatta desu'],
        ['持ち帰りでお願いします。', 'Para viagem, por favor.', undefined, undefined, 'mochikaeri de onegaishimasu'],
      ]),
    lesson('u2l3', '🔁', 'Minha rotina', 'O dia inteiro em 8 frases', undefined,
      [
        ['毎日七時に起きます。', 'Acordo às sete todo dia.', undefined, undefined, 'mainichi shichiji ni okimasu'],
        ['彼女は家で働いています。', 'Ela trabalha em casa.', 'で marca onde a ação acontece.', undefined, 'kanojo wa ie de hataraite imasu'],
        ['夜、日本語を勉強します。', 'À noite eu estudo japonês.', undefined, undefined, 'yoru, nihongo o benkyou shimasu'],
        ['朝ごはんはパンです。', 'Meu café da manhã é pão.', undefined, undefined, 'asagohan wa pan desu'],
        ['月曜日は出かけません。', 'Segunda-feira eu não saio.', undefined, undefined, 'getsuyoubi wa dekakemasen'],
        ['早起きが苦手です。', 'Sou péssima em acordar cedo.', '苦手 = não levo jeito para.', undefined, 'hayaoki ga nigate desu'],
        ['何時に寝ますか。', 'Que horas você dorme?', undefined, undefined, 'nanji ni nemasu ka'],
        ['日曜日はいつも疲れています。', 'Domingo estou sempre cansada.', undefined, undefined, 'nichiyoubi wa itsumo tsukarete imasu'],
      ]),
  ]),
  unit('u3', '町で', 'Sair e voltar inteira', 'A2', '#B8F000', [
    lesson('u3l1', '🧭', 'Achar o caminho', 'Direções e transporte', undefined,
      [
        ['トイレはどこですか。', 'Onde fica o banheiro?', undefined, undefined, 'toire wa doko desu ka'],
        ['駅までどう行きますか。', 'Como eu chego na estação?', 'まで = até.', undefined, 'eki made dou ikimasu ka'],
        ['まっすぐ行って、左に曲がってください。', 'Siga reto e vire à esquerda.', undefined, undefined, 'massugu itte, hidari ni magatte kudasai'],
        ['銀行の隣です。', 'É do lado do banco.', undefined, undefined, 'ginkou no tonari desu'],
        ['ここから遠いですか。', 'É longe daqui?', undefined, undefined, 'koko kara tooi desu ka'],
        ['歩いて十分です。', 'São dez minutos a pé.', undefined, undefined, 'aruite juppun desu'],
        ['道に迷いました。', 'Eu me perdi.', undefined, undefined, 'michi ni mayoimashita'],
        ['地図で見せてください。', 'Mostre no mapa, por favor.', undefined, undefined, 'chizu de misete kudasai'],
      ]),
    lesson('u3l2', '🛍️', 'Comprando', 'Loja, tamanho e preço', undefined,
      [
        ['見ているだけです。', 'Só estou olhando.', undefined, undefined, 'miteiru dake desu'],
        ['もっと小さいサイズはありますか。', 'Tem um tamanho menor?', undefined, undefined, 'motto chiisai saizu wa arimasu ka'],
        ['試着してもいいですか。', 'Posso experimentar?', 'てもいいですか = posso...?', undefined, 'shichaku shite mo ii desu ka'],
        ['高すぎます。', 'É caro demais.', 'すぎます = demais.', undefined, 'takasugimasu'],
        ['カードは使えますか。', 'Aceita cartão?', undefined, undefined, 'kaado wa tsukaemasu ka'],
        ['安くなりますか。', 'Fica mais barato? (tem desconto?)', undefined, undefined, 'yasuku narimasu ka'],
        ['返品したいです。', 'Quero devolver.', 'たいです = eu quero (fazer).', undefined, 'henpin shitai desu'],
        ['サイズが合いません。', 'O tamanho não serve.', undefined, undefined, 'saizu ga aimasen'],
      ]),
    lesson('u3l3', '🆘', 'Socorro', 'Quando dá ruim', undefined,
      [
        ['助けてください。', 'Me ajude, por favor.', undefined, undefined, 'tasukete kudasai'],
        ['携帯をなくしました。', 'Perdi meu celular.', undefined, undefined, 'keitai o nakushimashita'],
        ['財布を盗まれました。', 'Roubaram minha carteira.', 'Voz passiva: 盗まれました.', undefined, 'saifu o nusumaremashita'],
        ['救急車を呼んでください。', 'Chame uma ambulância!', undefined, undefined, 'kyuukyuusha o yonde kudasai'],
        ['気分が悪いです。', 'Não estou me sentindo bem.', undefined, undefined, 'kibun ga warui desu'],
        ['近くに薬局はありますか。', 'Tem farmácia por perto?', undefined, undefined, 'chikaku ni yakkyoku wa arimasu ka'],
        ['ピーナッツアレルギーです。', 'Sou alérgica a amendoim.', undefined, undefined, 'piinattsu arerugii desu'],
        ['緊急です。', 'É uma emergência.', undefined, undefined, 'kinkyuu desu'],
      ]),
  ]),
]
