// Curriculo de COREANO. Respostas aceitam hangul OU romanizacao.
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const KO_UNITS: Unit[] = [
  unit('u1', '첫 만남', 'Os primeiros 5 minutos', 'A1', '#C589E8', [
    lesson('u1l1', '👋', 'Cumprimentos', 'Oi, tchau e educação',
      { title: '요 é o seu escudo', body: 'Terminar em -요 deixa a frase educada e serve para quase tudo. Sem -요 (반말) só com amigos muito proximos ou gente mais nova. A ordem e sujeito - objeto - VERBO, com o verbo sempre no fim.' },
      [
        ['안녕하세요.', 'Olá.', 'Serve para bom dia, boa tarde e boa noite.', undefined, 'annyeonghaseyo'],
        ['만나서 반갑습니다.', 'Prazer em conhecer você.', undefined, undefined, 'mannaseo bangapseumnida'],
        ['어떻게 지내세요?', 'Como você está?', undefined, undefined, 'eotteoke jinaeseyo'],
        ['잘 지내요, 감사합니다.', 'Estou bem, obrigada.', undefined, undefined, 'jal jinaeyo, gamsahamnida'],
        ['이름이 뭐예요?', 'Qual é o seu nome?', undefined, undefined, 'ireumi mwoyeyo'],
        ['저는 아나예요.', 'Eu sou a Ana.', '저 é o "eu" humilde; 나 é o informal.', undefined, 'jeoneun ana yeyo'],
        ['나중에 봐요.', 'Até mais.', undefined, undefined, 'najunge bwayo'],
        ['안녕히 가세요.', 'Tchau. (para quem vai embora)', 'Quem fica ouve 안녕히 계세요. Trocar isso é o erro clássico.', undefined, 'annyeonghi gaseyo'],
      ]),
    lesson('u1l2', '🪪', 'Quem é você', 'Se apresentar', undefined,
      [
        ['저는 열여섯 살이에요.', 'Eu tenho dezesseis anos.', 'Idade usa os números coreanos nativos.', undefined, 'jeoneun yeollyeoseot sarieyo'],
        ['브라질에서 왔어요.', 'Eu vim do Brasil.', '에서 = de (origem).', undefined, 'beurajileseo wasseoyo'],
        ['상파울루에 살아요.', 'Eu moro em São Paulo.', undefined, undefined, 'sangpaullue sarayo'],
        ['저는 학생이에요.', 'Eu sou estudante.', undefined, undefined, 'jeoneun haksaengieyo'],
        ['형제가 두 명 있어요.', 'Eu tenho dois irmãos.', '명 é o contador de pessoas.', undefined, 'hyeongjega du myeong isseoyo'],
        ['이쪽은 제 친구 루카스예요.', 'Esse é meu amigo Lucas.', undefined, undefined, 'ijjogeun je chingu rukaseu yeyo'],
        ['한국어를 아직 잘 못해요.', 'Ainda não falo bem coreano.', undefined, undefined, 'hangugeoreul ajik jal mothaeyo'],
        ['다시 말해 주세요.', 'Fale de novo, por favor.', '주세요 = por favor, faça para mim.', undefined, 'dasi malhae juseyo'],
      ]),
    lesson('u1l3', '❓', 'Perguntas que salvam', 'Destravar a conversa', undefined,
      [
        ['이거 한국어로 뭐예요?', 'Como se diz isso em coreano?', undefined, undefined, 'igeo hangugeoro mwoyeyo'],
        ['무슨 뜻이에요?', 'O que significa?', undefined, undefined, 'museun tteusieyo'],
        ['천천히 말해 주세요.', 'Fale devagar, por favor.', undefined, undefined, 'cheoncheonhi malhae juseyo'],
        ['죄송해요, 못 알아들었어요.', 'Desculpa, não entendi.', undefined, undefined, 'joesonghaeyo, mot aradeureosseoyo'],
        ['한국어 할 줄 아세요?', 'Você sabe falar coreano?', undefined, undefined, 'hangugeo hal jul aseyo'],
        ['어디에서 왔어요?', 'De onde você é?', undefined, undefined, 'eodieseo wasseoyo'],
        ['무슨 일 하세요?', 'O que você faz da vida?', undefined, undefined, 'museun il haseyo'],
        ['괜찮아요?', 'Tudo bem? / Está tudo certo?', 'Palavra-curinga: serve para "tudo bem", "não precisa" e "ok".', undefined, 'gwaenchanayo'],
      ]),
  ]),
  unit('u2', '하루하루', 'Rotina, comida e horas', 'A1', '#F4A259', [
    lesson('u2l1', '⏰', 'Números e horas', 'Hora, preço, telefone',
      { title: 'Dois sistemas de número', body: 'Coreano tem DOIS conjuntos de números: nativos (하나, 둘, 셋 — para horas e idade) e sino-coreanos (일, 이, 삼 — para minutos, dinheiro, telefone). 7h30 = 일곱(nativo) 시 삼십(sino) 분.' },
      [
        ['지금 몇 시예요?', 'Que horas são?', undefined, undefined, 'jigeum myeot siyeyo'],
        ['일곱 시 반이에요.', 'São sete e meia.', '반 = meia.', undefined, 'ilgop si banieyo'],
        ['수업은 여덟 시에 시작해요.', 'A aula começa às oito.', undefined, undefined, 'sueobeun yeodeol sie sijakhaeyo'],
        ['얼마예요?', 'Quanto custa?', undefined, undefined, 'eolmayeyo'],
        ['만 원이에요.', 'São dez mil wons.', undefined, undefined, 'man wonieyo'],
        ['늦어서 죄송해요.', 'Desculpe o atraso.', undefined, undefined, 'neujeoseo joesonghaeyo'],
        ['여섯 시 반에 만나요.', 'A gente se encontra às seis e meia.', undefined, undefined, 'yeoseot si bane mannayo'],
        ['전화번호가 뭐예요?', 'Qual é o seu telefone?', undefined, undefined, 'jeonhwabeonhoga mwoyeyo'],
      ]),
    lesson('u2l2', '🍲', 'No restaurante', 'Pedir comida', undefined,
      [
        ['커피 주세요.', 'Um café, por favor.', undefined, undefined, 'keopi juseyo'],
        ['메뉴판 주세요.', 'O cardápio, por favor.', undefined, undefined, 'menyupan juseyo'],
        ['배고파요.', 'Estou com fome.', undefined, undefined, 'baegopayo'],
        ['매워요?', 'É apimentado?', 'Pergunta de sobrevivência na Coreia.', undefined, 'maewoyo'],
        ['고기 안 먹어요.', 'Eu não como carne.', '안 antes do verbo = não.', undefined, 'gogi an meogeoyo'],
        ['계산서 주세요.', 'A conta, por favor.', undefined, undefined, 'gyesanseo juseyo'],
        ['맛있었어요.', 'Estava delicioso.', undefined, undefined, 'masisseosseoyo'],
        ['포장해 주세요.', 'Para viagem, por favor.', undefined, undefined, 'pojanghae juseyo'],
      ]),
    lesson('u2l3', '🔁', 'Minha rotina', 'O dia inteiro', undefined,
      [
        ['일곱 시에 일어나요.', 'Eu acordo às sete.', undefined, undefined, 'ilgop sie ireonayo'],
        ['그녀는 집에서 일해요.', 'Ela trabalha em casa.', undefined, undefined, 'geunyeoneun jibeseo ilhaeyo'],
        ['밤에 한국어를 공부해요.', 'À noite eu estudo coreano.', undefined, undefined, 'bame hangugeoreul gongbuhaeyo'],
        ['아침에 커피를 마셔요.', 'De manhã eu tomo café.', undefined, undefined, 'achime keopireul masyeoyo'],
        ['월요일에는 안 나가요.', 'Às segundas eu não saio.', undefined, undefined, 'woryoireneun an nagayo'],
        ['일찍 일어나는 게 싫어요.', 'Odeio acordar cedo.', undefined, undefined, 'iljjik ireonaneun ge sireoyo'],
        ['몇 시에 자요?', 'Que horas você dorme?', undefined, undefined, 'myeot sie jayo'],
        ['일요일에는 항상 피곤해요.', 'Aos domingos estou sempre cansada.', undefined, undefined, 'iryoireneun hangsang pigonhaeyo'],
      ]),
  ]),
  unit('u3', '길에서', 'Sair e voltar inteira', 'A2', '#4ECDC4', [
    lesson('u3l1', '🧭', 'Achar o caminho', 'Direções', undefined,
      [
        ['화장실이 어디예요?', 'Onde fica o banheiro?', undefined, undefined, 'hwajangsiri eodiyeyo'],
        ['역까지 어떻게 가요?', 'Como eu chego na estação?', undefined, undefined, 'yeokkaji eotteoke gayo'],
        ['직진하고 왼쪽으로 가세요.', 'Siga reto e vá para à esquerda.', undefined, undefined, 'jikjinhago oenjjogeuro gaseyo'],
        ['은행 옆에 있어요.', 'Fica ao lado do banco.', undefined, undefined, 'eunhaeng yeope isseoyo'],
        ['여기서 멀어요?', 'É longe daqui?', undefined, undefined, 'yeogiseo meoreoyo'],
        ['걸어서 십 분이에요.', 'São dez minutos a pé.', undefined, undefined, 'georeoseo sip bunieyo'],
        ['길을 잃었어요.', 'Eu me perdi.', undefined, undefined, 'gireul ireosseoyo'],
        ['지도에서 보여 주세요.', 'Mostre no mapa, por favor.', undefined, undefined, 'jidoeseo boyeo juseyo'],
      ]),
    lesson('u3l2', '🛍️', 'Comprando', 'Loja e preço', undefined,
      [
        ['그냥 구경하는 거예요.', 'Só estou olhando.', undefined, undefined, 'geunyang gugyeonghaneun geoyeyo'],
        ['더 작은 사이즈 있어요?', 'Tem um tamanho menor?', undefined, undefined, 'deo jageun saijeu isseoyo'],
        ['입어 봐도 돼요?', 'Posso experimentar?', '~아/어 봐도 돼요? = posso experimentar...?', undefined, 'ibeo bwado dwaeyo'],
        ['너무 비싸요.', 'É caro demais.', undefined, undefined, 'neomu bissayo'],
        ['카드 돼요?', 'Aceita cartão?', undefined, undefined, 'kadeu dwaeyo'],
        ['깎아 주세요.', 'Me dá um desconto.', undefined, undefined, 'kkakka juseyo'],
        ['환불하고 싶어요.', 'Quero o reembolso.', undefined, undefined, 'hwanbulhago sipeoyo'],
        ['저한테 안 맞아요.', 'Não serve em mim.', undefined, undefined, 'jeohante an majayo'],
      ]),
    lesson('u3l3', '🆘', 'Socorro', 'Quando dá ruim', undefined,
      [
        ['도와주세요!', 'Me ajuda!', undefined, undefined, 'dowajuseyo'],
        ['휴대폰을 잃어버렸어요.', 'Perdi meu celular.', undefined, undefined, 'hyudaeponeul ireobeoryeosseoyo'],
        ['지갑을 도둑맞았어요.', 'Roubaram minha carteira.', undefined, undefined, 'jigabeul dodungmajasseoyo'],
        ['구급차를 불러 주세요!', 'Chame uma ambulância!', undefined, undefined, 'gugeupchareul bulleo juseyo'],
        ['몸이 안 좋아요.', 'Não estou me sentindo bem.', undefined, undefined, 'momi an joayo'],
        ['근처에 약국 있어요?', 'Tem farmácia por perto?', undefined, undefined, 'geuncheoe yakguk isseoyo'],
        ['땅콩 알레르기가 있어요.', 'Tenho alergia a amendoim.', undefined, undefined, 'ttangkong allereugiga isseoyo'],
        ['응급 상황이에요.', 'É uma emergência.', undefined, undefined, 'eunggeup sanghwangieyo'],
      ]),
  ]),
]
