// Curriculo de RUSSO. Respostas aceitam cirilico OU transliteracao.
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const RU_UNITS: Unit[] = [
  unit('u1', 'Первый контакт', 'Os primeiros 5 minutos', 'A1', '#6E8CA8', [
    lesson('u1l1', '👋', 'Cumprimentos', 'Oi formal e informal',
      { title: 'Ты x Вы', body: 'ТЫ com amigos e família. ВЫ com desconhecidos e mais velhos (e também plural). Detalhe que assusta: no presente o verbo SER simplesmente não existe — "Я студентка" = "eu (sou) estudante".' },
      [
        ['Привет!', 'Oi! (informal)', undefined, undefined, 'privet'],
        ['Здравствуйте.', 'Olá. (formal)', 'Palavra difícil de propósito: vale treinar em voz alta.', undefined, 'zdravstvuyte'],
        ['Как дела?', 'Como vai?', undefined, undefined, 'kak dela'],
        ['Хорошо, спасибо. А у тебя?', 'Bem, obrigada. E você?', undefined, undefined, 'khorosho, spasibo. a u tebya'],
        ['Как тебя зовут?', 'Qual é o seu nome?', 'Literal: "como te chamam".', undefined, 'kak tebya zovut'],
        ['Меня зовут Ана.', 'Meu nome é Ana.', undefined, undefined, 'menya zovut ana'],
        ['До свидания.', 'Até logo.', undefined, undefined, 'do svidaniya'],
        ['Доброе утро.', 'Bom dia.', undefined, undefined, 'dobroe utro'],
      ]),
    lesson('u1l2', '🪪', 'Quem é você', 'Se apresentar', undefined,
      [
        ['Мне шестнадцать лет.', 'Eu tenho dezesseis anos.', 'Idade em russo é no dativo: "a mim são 16 anos".', undefined, 'mne shestnadtsat let'],
        ['Я из Бразилии.', 'Eu sou do Brasil.', undefined, undefined, 'ya iz brazilii'],
        ['Я живу в Сан-Паулу.', 'Eu moro em São Paulo.', undefined, undefined, 'ya zhivu v san-paulu'],
        ['Я студентка.', 'Eu sou estudante.', 'Sem verbo: o "sou" não aparece no presente.', undefined, 'ya studentka'],
        ['У меня два брата.', 'Eu tenho dois irmãos.', 'Ter = "у меня" (junto a mim).', undefined, 'u menya dva brata'],
        ['Это мой друг Лукас.', 'Esse é meu amigo Lucas.', undefined, undefined, 'eto moy drug lukas'],
        ['Я ещё плохо говорю по-русски.', 'Ainda falo russo mal.', undefined, undefined, 'ya eshchyo plokho govoryu po-russki'],
        ['Повторите, пожалуйста.', 'Repita, por favor.', undefined, undefined, 'povtorite, pozhaluysta'],
      ]),
    lesson('u1l3', '❓', 'Perguntas que salvam', 'Destravar a conversa', undefined,
      [
        ['Как это сказать по-русски?', 'Como se diz isso em russo?', undefined, undefined, 'kak eto skazat po-russki'],
        ['Что это значит?', 'O que isso significa?', undefined, undefined, 'chto eto znachit'],
        ['Говорите медленнее, пожалуйста.', 'Fale mais devagar, por favor.', undefined, undefined, 'govorite medlennee, pozhaluysta'],
        ['Извините, я не поняла.', 'Desculpe, não entendi.', 'Mulher diz "не поняла"; homem, "не понял".', undefined, 'izvinite, ya ne ponyala'],
        ['Вы говорите по-русски?', 'Você fala russo?', undefined, undefined, 'vy govorite po-russki'],
        ['Откуда вы?', 'De onde você é?', undefined, undefined, 'otkuda vy'],
        ['Кем вы работаете?', 'Em que você trabalha?', undefined, undefined, 'kem vy rabotaete'],
        ['Почему вы спрашиваете?', 'Por que você pergunta?', undefined, undefined, 'pochemu vy sprashivaete'],
      ]),
  ]),
  unit('u2', 'Каждый день', 'Rotina, comida e horas', 'A1', '#FFB200', [
    lesson('u2l1', '⏰', 'Números e horas', 'Hora, preço, telefone', undefined,
      [
        ['Сколько сейчас времени?', 'Que horas são agora?', undefined, undefined, 'skolko seychas vremeni'],
        ['Сейчас семь тридцать.', 'São sete e trinta.', undefined, undefined, 'seychas sem tridtsat'],
        ['Урок начинается в восемь.', 'A aula começa às oito.', undefined, undefined, 'urok nachinaetsya v vosem'],
        ['Сколько это стоит?', 'Quanto custa isso?', undefined, undefined, 'skolko eto stoit'],
        ['Двадцать рублей.', 'Vinte rublos.', undefined, undefined, 'dvadtsat rubley'],
        ['Извините, я опоздала.', 'Desculpe, estou atrasada.', undefined, undefined, 'izvinite, ya opozdala'],
        ['Встретимся в шесть тридцать.', 'A gente se encontra às seis e trinta.', undefined, undefined, 'vstretimsya v shest tridtsat'],
        ['Мой номер телефона...', 'Meu número de telefone é...', undefined, undefined, 'moy nomer telefona'],
      ]),
    lesson('u2l2', '🥟', 'No restaurante', 'Pedir comida', undefined,
      [
        ['Кофе, пожалуйста.', 'Um café, por favor.', undefined, undefined, 'kofe, pozhaluysta'],
        ['Можно меню?', 'Pode trazer o cardápio?', undefined, undefined, 'mozhno menyu'],
        ['Я голодная.', 'Estou com fome.', undefined, undefined, 'ya golodnaya'],
        ['Это острое?', 'Isso é apimentado?', undefined, undefined, 'eto ostroe'],
        ['Я не ем мясо.', 'Eu não como carne.', undefined, undefined, 'ya ne em myaso'],
        ['Счёт, пожалуйста.', 'A conta, por favor.', undefined, undefined, 'schyot, pozhaluysta'],
        ['Было очень вкусно.', 'Estava muito gostoso.', undefined, undefined, 'bylo ochen vkusno'],
        ['С собой, пожалуйста.', 'Para viagem, por favor.', undefined, undefined, 's soboy, pozhaluysta'],
      ]),
    lesson('u2l3', '🔁', 'Minha rotina', 'O dia inteiro', undefined,
      [
        ['Я встаю в семь.', 'Eu levanto às sete.', undefined, undefined, 'ya vstayu v sem'],
        ['Она работает дома.', 'Ela trabalha em casa.', undefined, undefined, 'ona rabotaet doma'],
        ['Он учит русский вечером.', 'Ele estuda russo à noite.', undefined, undefined, 'on uchit russkiy vecherom'],
        ['Утром я пью кофе.', 'De manhã eu tomo café.', undefined, undefined, 'utrom ya pyu kofe'],
        ['Мы никогда не выходим в понедельник.', 'A gente nunca sai na segunda.', 'Dupla negativa é obrigatória: никогда + не.', undefined, 'my nikogda ne vykhodim v ponedelnik'],
        ['Мой брат ненавидит рано вставать.', 'Meu irmão odeia acordar cedo.', undefined, undefined, 'moy brat nenavidit rano vstavat'],
        ['Во сколько ты ложишься спать?', 'Que horas você vai dormir?', undefined, undefined, 'vo skolko ty lozhishsya spat'],
        ['В воскресенье я всегда уставшая.', 'No domingo eu estou sempre cansada.', undefined, undefined, 'v voskresenye ya vsegda ustavshaya'],
      ]),
  ]),
  unit('u3', 'На улице', 'Sair e voltar inteira', 'A2', '#8A8F98', [
    lesson('u3l1', '🧭', 'Achar o caminho', 'Direções', undefined,
      [
        ['Извините, где туалет?', 'Com licença, onde fica o banheiro?', undefined, undefined, 'izvinite, gde tualet'],
        ['Как добраться до вокзала?', 'Como eu chego na estação?', undefined, undefined, 'kak dobratsya do vokzala'],
        ['Идите прямо, потом налево.', 'Vá reto e depois à esquerda.', undefined, undefined, 'idite pryamo, potom nalevo'],
        ['Это рядом с банком.', 'Fica ao lado do banco.', undefined, undefined, 'eto ryadom s bankom'],
        ['Это далеко отсюда?', 'É longe daqui?', undefined, undefined, 'eto daleko otsyuda'],
        ['Десять минут пешком.', 'Dez minutos a pé.', undefined, undefined, 'desyat minut peshkom'],
        ['Я заблудилась.', 'Eu me perdi.', undefined, undefined, 'ya zabludilas'],
        ['Покажите на карте, пожалуйста.', 'Mostre no mapa, por favor.', undefined, undefined, 'pokazhite na karte, pozhaluysta'],
      ]),
    lesson('u3l2', '🛍️', 'Comprando', 'Loja e preço', undefined,
      [
        ['Я просто смотрю.', 'Só estou olhando.', undefined, undefined, 'ya prosto smotryu'],
        ['Есть размер поменьше?', 'Tem um tamanho menor?', undefined, undefined, 'est razmer pomenshe'],
        ['Можно примерить?', 'Posso experimentar?', undefined, undefined, 'mozhno primerit'],
        ['Это слишком дорого.', 'Isso é caro demais.', undefined, undefined, 'eto slishkom dorogo'],
        ['Вы принимаете карту?', 'Vocês aceitam cartão?', undefined, undefined, 'vy prinimaete kartu'],
        ['Есть скидка?', 'Tem desconto?', undefined, undefined, 'est skidka'],
        ['Я хочу вернуть это.', 'Quero devolver isso.', undefined, undefined, 'ya khochu vernut eto'],
        ['Не подходит.', 'Não serve.', undefined, undefined, 'ne podkhodit'],
      ]),
    lesson('u3l3', '🆘', 'Socorro', 'Quando dá ruim', undefined,
      [
        ['Помогите, пожалуйста!', 'Me ajude, por favor!', undefined, undefined, 'pomogite, pozhaluysta'],
        ['Я потеряла телефон.', 'Perdi meu telefone.', undefined, undefined, 'ya poteryala telefon'],
        ['У меня украли кошелёк.', 'Roubaram minha carteira.', undefined, undefined, 'u menya ukrali koshelyok'],
        ['Вызовите скорую!', 'Chame uma ambulância!', undefined, undefined, 'vyzovite skoruyu'],
        ['Мне плохо.', 'Estou passando mal.', undefined, undefined, 'mne plokho'],
        ['Здесь есть аптека?', 'Tem farmácia aqui?', undefined, undefined, 'zdes est apteka'],
        ['У меня аллергия на арахис.', 'Tenho alergia a amendoim.', undefined, undefined, 'u menya allergiya na arakhis'],
        ['Это срочно.', 'Isso é urgente.', undefined, undefined, 'eto srochno'],
      ]),
  ]),
]
