// Curriculo de MANDARIM. Respostas aceitam hanzi OU pinyin (com ou sem tom).
import type { Unit } from '../../state/types'
import { lesson, unit } from '../build'

export const ZH_UNITS: Unit[] = [
  unit('u1', '初次见面', 'Os primeiros 5 minutos', 'A1', '#FF2E2E', [
    lesson('u1l1', '👋', 'Cumprimentos', 'Oi, prazer e tchau',
      { title: 'Os 4 tons', body: 'A MESMA sílaba muda de sentido com o tom: mā (mãe), má (cânhamo), mǎ (cavalo), mà (xingar). Aqui você pode digitar o pinyin sem os acentos, mas ouca sempre o audio: o tom e metade da palavra.' },
      [
        ['你好！', 'Olá!', undefined, undefined, 'nǐ hǎo'],
        ['你好吗？', 'Como vai você?', '吗 transforma qualquer frase em pergunta.', undefined, 'nǐ hǎo ma'],
        ['我很好，谢谢。你呢？', 'Estou bem, obrigada. E você?', '呢 = "e você?".', undefined, 'wǒ hěn hǎo, xièxie. nǐ ne'],
        ['很高兴认识你。', 'Prazer em conhecer você.', undefined, undefined, 'hěn gāoxìng rènshi nǐ'],
        ['你叫什么名字？', 'Qual é o seu nome?', undefined, undefined, 'nǐ jiào shénme míngzi'],
        ['我叫安娜。', 'Eu me chamo Ana.', undefined, undefined, 'wǒ jiào ānnà'],
        ['回头见！', 'Até mais!', undefined, undefined, 'huítóu jiàn'],
        ['早上好。', 'Bom dia.', undefined, undefined, 'zǎoshang hǎo'],
      ]),
    lesson('u1l2', '🪪', 'Quem é você', 'Se apresentar', undefined,
      [
        ['我十六岁。', 'Eu tenho dezesseis anos.', 'Idade não usa verbo: só 我 + número + 岁.', undefined, 'wǒ shíliù suì'],
        ['我来自巴西。', 'Eu venho do Brasil.', undefined, undefined, 'wǒ láizì bāxī'],
        ['我住在圣保罗。', 'Eu moro em São Paulo.', undefined, undefined, 'wǒ zhù zài shèngbǎoluó'],
        ['我是学生。', 'Eu sou estudante.', undefined, undefined, 'wǒ shì xuésheng'],
        ['我有两个哥哥。', 'Eu tenho dois irmãos mais velhos.', 'Antes de contador usa-se 两, não 二.', undefined, 'wǒ yǒu liǎng gè gēge'],
        ['这是我的朋友卢卡斯。', 'Esse é meu amigo Lucas.', undefined, undefined, 'zhè shì wǒ de péngyou lúkǎsī'],
        ['我的中文还不好。', 'Meu chinês ainda não é bom.', undefined, undefined, 'wǒ de zhōngwén hái bù hǎo'],
        ['请再说一遍。', 'Repita, por favor.', undefined, undefined, 'qǐng zài shuō yī biàn'],
      ]),
    lesson('u1l3', '❓', 'Perguntas que salvam', 'Destravar a conversa', undefined,
      [
        ['这个用中文怎么说？', 'Como se diz isso em chinês?', undefined, undefined, 'zhège yòng zhōngwén zěnme shuō'],
        ['这是什么意思？', 'O que isso significa?', undefined, undefined, 'zhè shì shénme yìsi'],
        ['请说慢一点。', 'Fale mais devagar, por favor.', undefined, undefined, 'qǐng shuō màn yīdiǎn'],
        ['对不起，我没听懂。', 'Desculpa, eu não entendi.', undefined, undefined, 'duìbuqǐ, wǒ méi tīngdǒng'],
        ['你会说中文吗？', 'Você fala chinês?', '会 = saber fazer (habilidade).', undefined, 'nǐ huì shuō zhōngwén ma'],
        ['你是哪里人？', 'De onde você é?', undefined, undefined, 'nǐ shì nǎlǐ rén'],
        ['你做什么工作？', 'O que você faz da vida?', undefined, undefined, 'nǐ zuò shénme gōngzuò'],
        ['为什么问？', 'Por que você pergunta?', undefined, undefined, 'wèishénme wèn'],
      ]),
  ]),
  unit('u2', '每天', 'Rotina, comida e horas', 'A1', '#B8F000', [
    lesson('u2l1', '⏰', 'Números e horas', 'Hora, preço, telefone', undefined,
      [
        ['现在几点？', 'Que horas são?', undefined, undefined, 'xiànzài jǐ diǎn'],
        ['七点半。', 'Sete e meia.', '半 = meia.', undefined, 'qī diǎn bàn'],
        ['八点上课。', 'A aula começa às oito.', undefined, undefined, 'bā diǎn shàngkè'],
        ['多少钱？', 'Quanto custa?', undefined, undefined, 'duōshao qián'],
        ['二十块。', 'Vinte reais/yuans.', '块 é o "real" da fala; 元 é o formal.', undefined, 'èrshí kuài'],
        ['对不起，我迟到了。', 'Desculpa, estou atrasada.', undefined, undefined, 'duìbuqǐ, wǒ chídào le'],
        ['六点半见。', 'Até às seis e meia.', undefined, undefined, 'liù diǎn bàn jiàn'],
        ['我的电话号码是…', 'Meu telefone é...', undefined, undefined, 'wǒ de diànhuà hàomǎ shì'],
      ]),
    lesson('u2l2', '🥟', 'No restaurante', 'Pedir comida', undefined,
      [
        ['我要一杯咖啡。', 'Eu quero um café.', '杯 é o contador de copos.', undefined, 'wǒ yào yī bēi kāfēi'],
        ['请给我菜单。', 'Me dê o cardápio, por favor.', undefined, undefined, 'qǐng gěi wǒ càidān'],
        ['我饿了。', 'Estou com fome.', '了 marca mudança de estado.', undefined, 'wǒ è le'],
        ['这个辣吗？', 'Isso é apimentado?', undefined, undefined, 'zhège là ma'],
        ['我不吃肉。', 'Eu não como carne.', undefined, undefined, 'wǒ bù chī ròu'],
        ['买单！', 'A conta!', undefined, undefined, 'mǎidān'],
        ['很好吃，谢谢。', 'Muito gostoso, obrigada.', '好吃 é só para comida; bebida é 好喝.', undefined, 'hěn hǎochī, xièxie'],
        ['打包，谢谢。', 'Para viagem, obrigada.', undefined, undefined, 'dǎbāo, xièxie'],
      ]),
    lesson('u2l3', '🔁', 'Minha rotina', 'O dia inteiro', undefined,
      [
        ['我每天七点起床。', 'Eu acordo às sete todo dia.', 'Tempo vem ANTES do verbo em chinês.', undefined, 'wǒ měitiān qī diǎn qǐchuáng'],
        ['她在家工作。', 'Ela trabalha em casa.', undefined, undefined, 'tā zài jiā gōngzuò'],
        ['他晚上学中文。', 'Ele estuda chinês à noite.', undefined, undefined, 'tā wǎnshang xué zhōngwén'],
        ['我早上喝咖啡。', 'De manhã eu tomo café.', undefined, undefined, 'wǒ zǎoshang hē kāfēi'],
        ['我们星期一不出去。', 'Na segunda a gente não sai.', undefined, undefined, 'wǒmen xīngqīyī bù chūqù'],
        ['我弟弟不喜欢早起。', 'Meu irmão mais novo não gosta de acordar cedo.', undefined, undefined, 'wǒ dìdi bù xǐhuan zǎoqǐ'],
        ['你几点睡觉？', 'Que horas você dorme?', undefined, undefined, 'nǐ jǐ diǎn shuìjiào'],
        ['星期天我总是很累。', 'Domingo eu estou sempre cansada.', undefined, undefined, 'xīngqītiān wǒ zǒngshì hěn lèi'],
      ]),
  ]),
  unit('u3', '在街上', 'Sair e voltar inteira', 'A2', '#6E8CA8', [
    lesson('u3l1', '🧭', 'Achar o caminho', 'Direções', undefined,
      [
        ['洗手间在哪里？', 'Onde fica o banheiro?', undefined, undefined, 'xǐshǒujiān zài nǎlǐ'],
        ['怎么去车站？', 'Como eu vou para a estação?', undefined, undefined, 'zěnme qù chēzhàn'],
        ['一直走，然后左转。', 'Siga reto e depois vire à esquerda.', undefined, undefined, 'yīzhí zǒu, ránhòu zuǒ zhuǎn'],
        ['在银行旁边。', 'Fica ao lado do banco.', undefined, undefined, 'zài yínháng pángbiān'],
        ['离这里远吗？', 'É longe daqui?', undefined, undefined, 'lí zhèlǐ yuǎn ma'],
        ['走路十分钟。', 'Dez minutos a pé.', undefined, undefined, 'zǒulù shí fēnzhōng'],
        ['我迷路了。', 'Eu me perdi.', undefined, undefined, 'wǒ mílù le'],
        ['请在地图上指给我看。', 'Mostre no mapa, por favor.', undefined, undefined, 'qǐng zài dìtú shàng zhǐ gěi wǒ kàn'],
      ]),
    lesson('u3l2', '🛍️', 'Comprando', 'Loja e pechincha', undefined,
      [
        ['我只是看看。', 'Só estou olhando.', 'Repetir o verbo suaviza: 看看 = dar uma olhadinha.', undefined, 'wǒ zhǐshì kànkan'],
        ['有小一点的吗？', 'Tem um pouco menor?', undefined, undefined, 'yǒu xiǎo yīdiǎn de ma'],
        ['可以试穿吗？', 'Posso experimentar?', undefined, undefined, 'kěyǐ shìchuān ma'],
        ['太贵了。', 'Caro demais.', '太...了 = demais.', undefined, 'tài guì le'],
        ['可以刷卡吗？', 'Aceita cartão?', undefined, undefined, 'kěyǐ shuākǎ ma'],
        ['能便宜一点吗？', 'Dá para fazer mais barato?', undefined, undefined, 'néng piányi yīdiǎn ma'],
        ['我想退货。', 'Quero devolver.', undefined, undefined, 'wǒ xiǎng tuìhuò'],
        ['不合适。', 'Não ficou bom / não serve.', undefined, undefined, 'bù héshì'],
      ]),
    lesson('u3l3', '🆘', 'Socorro', 'Quando dá ruim', undefined,
      [
        ['请帮帮我！', 'Me ajuda, por favor!', undefined, undefined, 'qǐng bāngbang wǒ'],
        ['我的手机丢了。', 'Perdi meu celular.', undefined, undefined, 'wǒ de shǒujī diū le'],
        ['我的钱包被偷了。', 'Roubaram minha carteira.', '被 marca a voz passiva.', undefined, 'wǒ de qiánbāo bèi tōu le'],
        ['快叫救护车！', 'Chame uma ambulância, rápido!', undefined, undefined, 'kuài jiào jiùhùchē'],
        ['我不舒服。', 'Não estou me sentindo bem.', undefined, undefined, 'wǒ bù shūfu'],
        ['附近有药店吗？', 'Tem farmácia por perto?', undefined, undefined, 'fùjìn yǒu yàodiàn ma'],
        ['我对花生过敏。', 'Sou alérgica a amendoim.', undefined, undefined, 'wǒ duì huāshēng guòmǐn'],
        ['这是紧急情况。', 'Isso é uma emergência.', undefined, undefined, 'zhè shì jǐnjí qíngkuàng'],
      ]),
  ]),
]
